import type { Track } from "./types";

export const css: Track = {
  id: "css",
  name: "CSS",
  short: "Cs",
  blurb: "Color, space, and layout. Make HTML look like a product.",
  level: "Beginner",
  chapters: [
    {
      id: "1",
      title: "Selectors and color",
      summary: "Target elements and paint them.",
      clash: {
        name: "The Unstyled Page",
        blurb: "Every rule missed its target. Repair the selectors.",
      },
      lessons: [
        {
          id: "1",
          title: "A CSS rule",
          minutes: 3,
          teach: {
            title: "selector { property: value; }",
            body: "A rule has a selector (who), then braces. Inside: property, colon, value, semicolon. The browser applies matching rules to the HTML.",
            code: "p {\n  color: #eceee9;\n}",
          },
          terms: [
            { term: "selector", def: "The part that chooses which elements to style" },
            { term: "property", def: "What you change, like color or margin" },
            { term: "declaration", def: "A property: value; pair" },
          ],
          questions: [
            {
              id: "css-1-1-a",
              kind: "fill",
              prompt: "Open a rule for paragraphs.",
              code: "___ {\n  color: black;\n}",
              choices: ["p", "paragraph", "<p>", "text"],
              answer: "p",
              why: "The selector is the tag name without brackets: p.",
              concept: "rules",
            },
            {
              id: "css-1-1-b",
              kind: "choice",
              prompt: "Which line is a valid declaration?",
              choices: [
                "color: red;",
                "color red",
                "red: color;",
                "color = red;",
              ],
              answer: 0,
              why: "property, colon, value, semicolon.",
              concept: "rules",
            },
            {
              id: "css-1-1-c",
              kind: "bool",
              prompt: "CSS selectors use angle brackets like <p>.",
              answer: false,
              why: "HTML uses <p>. CSS uses p.",
              concept: "rules",
            },
          ],
        },
        {
          id: "2",
          title: "Classes and ids",
          minutes: 3,
          teach: {
            title: ".class and #id",
            body: "A class is reusable: HTML class=\"card\", CSS .card. An id should be unique: id=\"hero\", CSS #hero. Prefer classes for styling. ids are for unique hooks (labels, fragments).",
            code: ".card {\n  padding: 16px;\n}\n#hero {\n  font-size: 2rem;\n}",
          },
          terms: [
            { term: ".class", def: "Selector for a reusable class" },
            { term: "#id", def: "Selector for a unique id" },
          ],
          questions: [
            {
              id: "css-1-2-a",
              kind: "fill",
              prompt: "Select elements with class card.",
              code: "___ {\n  padding: 16px;\n}",
              choices: [".card", "#card", "card", "class.card"],
              answer: ".card",
              why: "A leading dot means class.",
              concept: "classes",
            },
            {
              id: "css-1-2-b",
              kind: "choice",
              prompt: "How do you select id=\"nav\"?",
              choices: ["#nav", ".nav", "nav", "id nav"],
              answer: 0,
              why: "# is the id selector.",
              concept: "classes",
            },
            {
              id: "css-1-2-c",
              kind: "bool",
              prompt: "A class can be used on many elements.",
              answer: true,
              why: "That is the point of classes. ids should stay unique.",
              concept: "classes",
            },
          ],
        },
        {
          id: "3",
          title: "Color",
          minutes: 3,
          teach: {
            title: "color vs background-color",
            body: "color paints text. background-color paints the box behind it. Hex like #0b0c0b, rgb(), or named colors all work. Change both when you change a background so contrast still holds.",
            code: "body {\n  background-color: #0b0c0b;\n  color: #eceee9;\n}",
          },
          terms: [
            { term: "color", def: "Text (foreground) color" },
            { term: "background-color", def: "Fill behind the content" },
          ],
          questions: [
            {
              id: "css-1-3-a",
              kind: "choice",
              prompt: "Which property colors the text?",
              choices: ["color", "background-color", "fill", "font-color"],
              answer: 0,
              why: "color is the text. There is no font-color in CSS.",
              concept: "color",
            },
            {
              id: "css-1-3-b",
              kind: "fill",
              prompt: "Paint the page background.",
              code: "body {\n  ___: #0b0c0b;\n}",
              choices: ["background-color", "color", "bg", "background-image"],
              answer: "background-color",
              why: "background-color fills the box. color would paint the words.",
              concept: "color",
            },
            {
              id: "css-1-3-c",
              kind: "bool",
              prompt: "If you change a background, you should also check the text color.",
              answer: true,
              why: "Contrast is a pair. One change can hide the other.",
              concept: "color",
            },
          ],
        },
      ],
    },
    {
      id: "2",
      title: "The box model",
      summary: "Padding, border, margin, width.",
      clash: {
        name: "Overflowed Box",
        blurb: "Margins collapsed and padding vanished. Rebuild the box.",
      },
      lessons: [
        {
          id: "1",
          title: "Inside, edge, outside",
          minutes: 4,
          teach: {
            title: "content → padding → border → margin",
            body: "Padding is space inside the border. Border is the edge. Margin is space outside, pushing neighbors away. width by default is the content width — padding and border add on. box-sizing: border-box includes them in width.",
            code: ".card {\n  padding: 16px;\n  border: 1px solid #eceee9;\n  margin: 12px;\n}",
          },
          terms: [
            { term: "padding", def: "Space inside the border" },
            { term: "margin", def: "Space outside the border" },
            { term: "border", def: "The visible (or invisible) edge" },
          ],
          questions: [
            {
              id: "css-2-1-a",
              kind: "choice",
              prompt: "Which is space inside the border?",
              choices: ["padding", "margin", "outline", "gap"],
              answer: 0,
              why: "Padding lives inside. Margin lives outside.",
              concept: "box-model",
            },
            {
              id: "css-2-1-b",
              kind: "fill",
              prompt: "Push this box away from its siblings.",
              code: ".card {\n  ___: 16px;\n}",
              choices: ["margin", "padding", "indent", "gap"],
              answer: "margin",
              why: "Margin is the outer gap between boxes.",
              concept: "box-model",
            },
            {
              id: "css-2-1-c",
              kind: "bool",
              prompt: "With content-box, padding adds extra width on top of width.",
              answer: true,
              why: "That surprise is why most apps set box-sizing: border-box.",
              concept: "box-model",
            },
          ],
        },
        {
          id: "2",
          title: "Display",
          minutes: 3,
          teach: {
            title: "block, inline, none",
            body: "block takes the full row (div, p, h1). inline sits in the text (span, a). none hides the element — it is not there for layout. inline-block is a hybrid: flows like text, accepts width and height.",
            code: "span { display: block; }\n.hidden { display: none; }",
          },
          terms: [
            { term: "block", def: "Starts on a new line, takes available width" },
            { term: "inline", def: "Sits in the text flow" },
            { term: "display: none", def: "Remove from layout entirely" },
          ],
          questions: [
            {
              id: "css-2-2-a",
              kind: "choice",
              prompt: "Which display hides an element from layout?",
              choices: ["none", "hidden", "block", "invisible"],
              answer: 0,
              why: "display: none. visibility: hidden would hide but keep the space.",
              concept: "display",
            },
            {
              id: "css-2-2-b",
              kind: "fill",
              prompt: "Make the span take a full row.",
              code: "span {\n  display: ___;\n}",
              choices: ["block", "inline", "none", "flex"],
              answer: "block",
              why: "display: block makes it behave like a paragraph.",
              concept: "display",
            },
            {
              id: "css-2-2-c",
              kind: "bool",
              prompt: "a is inline by default.",
              answer: true,
              why: "Links sit in the sentence unless you change display.",
              concept: "display",
            },
          ],
        },
        {
          id: "3",
          title: "Units",
          minutes: 3,
          teach: {
            title: "px, rem, %, vh",
            body: "px is an absolute-ish pixel. rem is relative to the root font size — scales when the user zooms text. % is relative to the parent. vh is 1% of the viewport height. Prefer rem for type, % or flex for layout.",
            code: "h1 { font-size: 2rem; }\n.hero { height: 100vh; }",
          },
          terms: [
            { term: "rem", def: "Size relative to the root font-size" },
            { term: "vh", def: "1% of the viewport height" },
          ],
          questions: [
            {
              id: "css-2-3-a",
              kind: "choice",
              prompt: "Which unit scales with the root font size?",
              choices: ["rem", "px", "vh", "cm"],
              answer: 0,
              why: "rem tracks html font-size. px does not.",
              concept: "units",
            },
            {
              id: "css-2-3-b",
              kind: "fill",
              prompt: "Make a full-viewport-height hero.",
              code: ".hero {\n  height: 100___;\n}",
              choices: ["vh", "rem", "%", "px"],
              answer: "vh",
              why: "100vh is the full window height.",
              concept: "units",
            },
            {
              id: "css-2-3-c",
              kind: "bool",
              prompt: "50% width is half of the viewport, always.",
              answer: false,
              why: "% is of the parent, which may be narrower than the viewport.",
              concept: "units",
            },
          ],
        },
      ],
    },
    {
      id: "3",
      title: "Flexbox layout",
      summary: "Rows, columns, alignment.",
      clash: {
        name: "The Crooked Row",
        blurb: "Items refuse to center. Recast justify and align.",
      },
      lessons: [
        {
          id: "1",
          title: "display: flex",
          minutes: 3,
          teach: {
            title: "A flex container lines up children",
            body: "Put display: flex on the parent. Children become flex items in a row by default. flex-direction: column stacks them. The parent is the container — properties like justify-content live there, not on each child.",
            code: ".row {\n  display: flex;\n  gap: 12px;\n}",
          },
          terms: [
            { term: "flex container", def: "The parent with display: flex" },
            { term: "gap", def: "Space between items, without extra margin math" },
          ],
          questions: [
            {
              id: "css-3-1-a",
              kind: "fill",
              prompt: "Turn the parent into a flex row.",
              code: ".row {\n  display: ___;\n}",
              choices: ["flex", "block", "grid", "inline"],
              answer: "flex",
              why: "display: flex on the parent enables flex layout.",
              concept: "flex",
            },
            {
              id: "css-3-1-b",
              kind: "choice",
              prompt: "Default flex-direction is",
              choices: ["row", "column", "wrap", "center"],
              answer: 0,
              why: "Items sit in a horizontal row unless you change it.",
              concept: "flex",
            },
            {
              id: "css-3-1-c",
              kind: "bool",
              prompt: "gap is set on the flex container, not each child.",
              answer: true,
              why: "gap is a container property.",
              concept: "flex",
            },
          ],
        },
        {
          id: "2",
          title: "Main axis vs cross axis",
          minutes: 4,
          teach: {
            title: "justify-content and align-items",
            body: "In a row, the main axis is horizontal — justify-content packs along it (center, space-between, flex-end). The cross axis is vertical — align-items (center, flex-start, stretch). Swap flex-direction to column and the axes swap too.",
            code: ".center {\n  display: flex;\n  justify-content: center;\n  align-items: center;\n}",
          },
          terms: [
            { term: "justify-content", def: "Alignment along the main axis" },
            { term: "align-items", def: "Alignment along the cross axis" },
          ],
          questions: [
            {
              id: "css-3-2-a",
              kind: "choice",
              prompt: "In a row, which property centers items horizontally?",
              choices: ["justify-content", "align-items", "text-align", "float"],
              answer: 0,
              why: "Row main axis is horizontal, so justify-content.",
              concept: "flex-align",
            },
            {
              id: "css-3-2-b",
              kind: "fill",
              prompt: "Center items on the cross axis.",
              code: ".row {\n  display: flex;\n  ___: center;\n}",
              choices: ["align-items", "justify-content", "align-content", "place-self"],
              answer: "align-items",
              why: "align-items is the cross axis (vertical in a row).",
              concept: "flex-align",
            },
            {
              id: "css-3-2-c",
              kind: "bool",
              prompt: "space-between puts equal space between items, not outside.",
              answer: true,
              why: "First and last items hug the edges. space-around / space-evenly differ.",
              concept: "flex-align",
            },
          ],
        },
        {
          id: "3",
          title: "flex on children",
          minutes: 3,
          teach: {
            title: "flex: 1 grows",
            body: "On an item, flex: 1 means grow to fill leftover space. flex-wrap: wrap on the container lets items drop to the next line instead of shrinking forever. min-width: 0 is the usual fix when a child refuses to shrink.",
            code: ".grow {\n  flex: 1;\n}\n.wrap {\n  display: flex;\n  flex-wrap: wrap;\n}",
          },
          terms: [
            { term: "flex: 1", def: "Grow to fill leftover space" },
            { term: "flex-wrap", def: "Allow items to move to the next line" },
          ],
          questions: [
            {
              id: "css-3-3-a",
              kind: "fill",
              prompt: "Let this item eat leftover space.",
              code: ".main {\n  flex: ___;\n}",
              choices: ["1", "0", "auto", "none"],
              answer: "1",
              why: "flex: 1 is the common grow pattern.",
              concept: "flex-children",
            },
            {
              id: "css-3-3-b",
              kind: "choice",
              prompt: "Stop items overflowing by wrapping them.",
              choices: ["flex-wrap: wrap", "flex-wrap: nowrap", "display: block", "float: left"],
              answer: 0,
              why: "wrap lets extra items move to the next line.",
              concept: "flex-children",
            },
            {
              id: "css-3-3-c",
              kind: "bool",
              prompt: "flex: 1 is set on the container.",
              answer: false,
              why: "Growth is a child property. The container sets display: flex.",
              concept: "flex-children",
            },
          ],
        },
      ],
    },
  ],
};
