import type { Track } from "./types";

export const git: Track = {
  id: "git",
  name: "Git",
  short: "Gt",
  blurb: "Save snapshots, branch safely, collaborate without chaos.",
  level: "Beginner",
  chapters: [
    {
      id: "1",
      title: "Save your work",
      summary: "init, status, add, commit.",
      clash: {
        name: "The Unstaged Past",
        blurb: "Nothing is committed. Rebuild the save loop.",
      },
      lessons: [
        {
          id: "1",
          title: "A repository",
          minutes: 3,
          teach: {
            title: "git init starts a project",
            body: "A repository is a folder Git is watching. git init creates the hidden .git directory. git status tells you what changed. You do not need a server to start — local commits are real commits.",
            code: "git init\ngit status",
          },
          terms: [
            { term: "repository", def: "A project folder tracked by Git" },
            { term: "git status", def: "Show changed, staged, and untracked files" },
          ],
          questions: [
            {
              id: "gt-1-1-a",
              kind: "fill",
              prompt: "Start tracking this folder.",
              code: "git ___",
              choices: ["init", "start", "new", "create"],
              answer: "init",
              why: "git init creates the repo.",
              concept: "init",
            },
            {
              id: "gt-1-1-b",
              kind: "choice",
              prompt: "See what changed with",
              choices: ["git status", "git log", "git diff --staged", "git init"],
              answer: 0,
              why: "status is the map. log is history. diff is the patch.",
              concept: "init",
            },
            {
              id: "gt-1-1-c",
              kind: "bool",
              prompt: "You need GitHub before you can commit.",
              answer: false,
              why: "Commits are local. Remotes are optional until you share.",
              concept: "init",
            },
          ],
        },
        {
          id: "2",
          title: "Stage then commit",
          minutes: 4,
          teach: {
            title: "Two steps on purpose",
            body: "git add path puts a change in the staging area (the next snapshot). git commit -m \"message\" freezes the staging area into history. You can add only some files so a commit is one idea, not a dump of the afternoon.",
            code: "git add index.html\ngit commit -m \"Add the home page\"",
          },
          terms: [
            { term: "staging area", def: "The files that will be in the next commit" },
            { term: "commit", def: "A snapshot with a message and a parent" },
          ],
          questions: [
            {
              id: "gt-1-2-a",
              kind: "fill",
              prompt: "Stage index.html.",
              code: "git ___ index.html",
              choices: ["add", "commit", "stage", "save"],
              answer: "add",
              why: "add stages. commit records.",
              concept: "commit",
            },
            {
              id: "gt-1-2-b",
              kind: "choice",
              prompt: "Write a snapshot with a message.",
              choices: [
                'git commit -m "Fix login"',
                "git add -m \"Fix login\"",
                "git save \"Fix login\"",
                "git commit index.html",
              ],
              answer: 0,
              why: "commit -m records whatever is staged.",
              concept: "commit",
            },
            {
              id: "gt-1-2-c",
              kind: "order",
              prompt: "Save a file the usual way.",
              choices: ["git add app.js", 'git commit -m "Handle empty input"'],
              why: "Stage first, then commit. Committing with nothing staged is a no-op (or an error).",
              concept: "commit",
            },
          ],
        },
        {
          id: "3",
          title: "log and diff",
          minutes: 3,
          teach: {
            title: "Read history and changes",
            body: "git log lists commits, newest first. git diff shows unstaged changes. git diff --staged shows what the next commit would include. Read before you commit.",
            code: "git log --oneline\ngit diff",
          },
          terms: [
            { term: "git log", def: "List commits" },
            { term: "git diff", def: "Show what changed" },
          ],
          questions: [
            {
              id: "gt-1-3-a",
              kind: "choice",
              prompt: "See commit history with",
              choices: ["git log", "git status", "git init", "git add"],
              answer: 0,
              why: "log is history. status is the working tree right now.",
              concept: "log",
            },
            {
              id: "gt-1-3-b",
              kind: "fill",
              prompt: "Show unstaged changes.",
              code: "git ___",
              choices: ["diff", "log", "show", "status"],
              answer: "diff",
              why: "diff is the patch. status only lists names.",
              concept: "log",
            },
            {
              id: "gt-1-3-c",
              kind: "bool",
              prompt: "git diff --staged previews the next commit.",
              answer: true,
              why: "It diffs the staging area against HEAD.",
              concept: "log",
            },
          ],
        },
      ],
    },
    {
      id: "2",
      title: "Branches and remotes",
      summary: "branch, switch, merge, push, pull.",
      clash: {
        name: "Detached HEAD",
        blurb: "You are not on a branch. Find main again.",
      },
      lessons: [
        {
          id: "1",
          title: "Branches",
          minutes: 4,
          teach: {
            title: "A movable label on a commit",
            body: "A branch is a name pointing at a commit. git branch feature creates one. git switch feature (or git checkout) moves you there. New commits advance the branch you are on. main (or master) is just a branch with a familiar name.",
            code: "git branch feature\ngit switch feature",
          },
          terms: [
            { term: "branch", def: "A named pointer to a commit" },
            { term: "git switch", def: "Move to another branch" },
          ],
          questions: [
            {
              id: "gt-2-1-a",
              kind: "fill",
              prompt: "Create a branch called feature.",
              code: "git ___ feature",
              choices: ["branch", "new", "create", "fork"],
              answer: "branch",
              why: "git branch names a new pointer. You still have to switch.",
              concept: "branches",
            },
            {
              id: "gt-2-1-b",
              kind: "choice",
              prompt: "Move onto feature with",
              choices: ["git switch feature", "git branch feature", "git commit feature", "git log feature"],
              answer: 0,
              why: "switch (or checkout) changes HEAD to that branch.",
              concept: "branches",
            },
            {
              id: "gt-2-1-c",
              kind: "bool",
              prompt: "Commits always go to main, even on another branch.",
              answer: false,
              why: "Commits advance the current branch.",
              concept: "branches",
            },
          ],
        },
        {
          id: "2",
          title: "Merge",
          minutes: 3,
          teach: {
            title: "Bring a branch home",
            body: "On main, git merge feature folds feature's commits in. A fast-forward just moves the pointer if main has not diverged. If both sides edited the same lines, Git asks you to resolve a conflict, then commit.",
            code: "git switch main\ngit merge feature",
          },
          terms: [
            { term: "merge", def: "Combine another branch into the current one" },
            { term: "conflict", def: "Both sides changed the same lines" },
          ],
          questions: [
            {
              id: "gt-2-2-a",
              kind: "order",
              prompt: "Merge feature into main.",
              choices: ["git switch main", "git merge feature"],
              why: "You merge into the branch you are on.",
              concept: "merge",
            },
            {
              id: "gt-2-2-b",
              kind: "choice",
              prompt: "A conflict means",
              choices: [
                "both branches changed the same part of a file",
                "Git deleted your repo",
                "the remote is down",
                "you forgot to add",
              ],
              answer: 0,
              why: "Git will not guess. You pick the result and commit.",
              concept: "merge",
            },
            {
              id: "gt-2-2-c",
              kind: "bool",
              prompt: "You merge while sitting on the branch you want to update.",
              answer: true,
              why: "switch to main, then merge feature.",
              concept: "merge",
            },
          ],
        },
        {
          id: "3",
          title: "Remotes",
          minutes: 3,
          teach: {
            title: "push and pull",
            body: "A remote is a nickname for another copy, often origin on GitHub. git push sends your commits. git pull fetches and merges what others pushed. clone copies an existing remote into a new local repo.",
            code: "git remote add origin git@github.com:you/app.git\ngit push -u origin main\ngit pull",
          },
          terms: [
            { term: "remote", def: "A named URL of another repository" },
            { term: "push", def: "Send local commits to a remote" },
            { term: "pull", def: "Fetch remote commits and merge them" },
          ],
          questions: [
            {
              id: "gt-2-3-a",
              kind: "fill",
              prompt: "Send commits to origin.",
              code: "git ___ origin main",
              choices: ["push", "pull", "send", "upload"],
              answer: "push",
              why: "push publishes. pull retrieves.",
              concept: "remotes",
            },
            {
              id: "gt-2-3-b",
              kind: "choice",
              prompt: "Copy an existing remote repo with",
              choices: ["git clone <url>", "git init <url>", "git add <url>", "git merge <url>"],
              answer: 0,
              why: "clone creates a local repo with that remote already set.",
              concept: "remotes",
            },
            {
              id: "gt-2-3-c",
              kind: "bool",
              prompt: "git pull is fetch plus merge.",
              answer: true,
              why: "It updates your current branch from its remote-tracking branch.",
              concept: "remotes",
            },
          ],
        },
      ],
    },
  ],
};
