import type { Track } from "./types";

export const html: Track = {
  id: "html",
  name: "HTML",
  short: "Ht",
  blurb: "The skeleton of every website. Tags, pages, structure.",
  level: "Beginner",
  chapters: [
    {
      id: "1",
      title: "Page skeleton",
      summary: "Documents, headings, and paragraphs.",
      clash: {
        name: "The Hollow Document",
        blurb: "Tags are missing their pairs. Close the structure.",
      },
      lessons: [
        {
          id: "1",
          title: "What a tag is",
          minutes: 3,
          teach: {
            title: "HTML wraps content in tags",
            body: "A tag looks like <p>. Most come in pairs: an opener and a closer with a slash, like </p>. The browser uses tags to know what each piece of content is — a heading, a paragraph, a link.",
            code: "<p>Hello, web.</p>",
          },
          terms: [
            { term: "tag", def: "A label in angle brackets, like <p>" },
            { term: "element", def: "A tag pair plus the content inside" },
          ],
          questions: [
            {
              id: "html-1-1-a",
              kind: "fill",
              prompt: "Close the paragraph.",
              code: "<p>Hello___",
              choices: ["</p>", "<p>", "</paragraph>", "<end>"],
              answer: "</p>",
              why: "Closers repeat the name with a slash: </p>.",
              concept: "tags",
            },
            {
              id: "html-1-1-b",
              kind: "choice",
              prompt: "Which is a valid paragraph?",
              choices: ["<p>Hi</p>", "<p>Hi<p>", "p Hi /p", "<paragraph>Hi</paragraph>"],
              answer: 0,
              why: "Open <p>, content, close </p>.",
              concept: "tags",
            },
            {
              id: "html-1-1-c",
              kind: "bool",
              prompt: "HTML tag names are case-sensitive.",
              answer: false,
              why: "Browsers treat <P> like <p>. Convention is lowercase.",
              concept: "tags",
            },
          ],
        },
        {
          id: "2",
          title: "The document",
          minutes: 3,
          teach: {
            title: "html, head, body",
            body: "<!DOCTYPE html> tells the browser this is modern HTML. <html> wraps everything. <head> holds metadata (title, charset). <body> holds what the visitor sees.",
            code: "<!DOCTYPE html>\n<html>\n  <head>\n    <title>Synapse</title>\n  </head>\n  <body>\n    <p>Hello</p>\n  </body>\n</html>",
          },
          terms: [
            { term: "<head>", def: "Metadata for the browser and search engines" },
            { term: "<body>", def: "Visible page content" },
            { term: "<title>", def: "Text in the browser tab" },
          ],
          questions: [
            {
              id: "html-1-2-a",
              kind: "choice",
              prompt: "Where does visible text go?",
              choices: ["<body>", "<head>", "<title>", "<!DOCTYPE html>"],
              answer: 0,
              why: "The body is the visible document. The head is behind-the-scenes.",
              concept: "document",
            },
            {
              id: "html-1-2-b",
              kind: "fill",
              prompt: "Set the tab text.",
              code: "<___>Synapse</title>",
              choices: ["title", "head", "name", "tab"],
              answer: "title",
              why: "The title element sets the tab label.",
              concept: "document",
            },
            {
              id: "html-1-2-c",
              kind: "order",
              prompt: "Build the outer shell in order.",
              choices: ["<!DOCTYPE html>", "<html>", "<head></head>", "<body></body>", "</html>"],
              why: "Doctype first, then html wrapping head then body.",
              concept: "document",
            },
          ],
        },
        {
          id: "3",
          title: "Headings and paragraphs",
          minutes: 3,
          teach: {
            title: "h1–h6 and p",
            body: "h1 is the main heading of the page — use one. h2, h3 step down for sections. p is a paragraph. Headings are structure, not a size knob. CSS handles looks.",
            code: "<h1>Synapse</h1>\n<h2>Python</h2>\n<p>Learn a little every day.</p>",
          },
          terms: [
            { term: "<h1>", def: "The main heading of a page" },
            { term: "<p>", def: "A paragraph of text" },
          ],
          questions: [
            {
              id: "html-1-3-a",
              kind: "choice",
              prompt: "Which tag is the page's main heading?",
              choices: ["<h1>", "<h6>", "<header>", "<p>"],
              answer: 0,
              why: "h1 is the top of the heading outline.",
              concept: "headings",
            },
            {
              id: "html-1-3-b",
              kind: "fill",
              prompt: "Make a section heading.",
              code: "<___>Chapter 1</h2>",
              choices: ["h2", "h1", "p", "b"],
              answer: "h2",
              why: "h2 sits under h1 for sections.",
              concept: "headings",
            },
            {
              id: "html-1-3-c",
              kind: "bool",
              prompt: "You should use many h1 tags per page for SEO.",
              answer: false,
              why: "One h1 keeps the outline clear. Use h2+ for the rest.",
              concept: "headings",
            },
          ],
        },
      ],
    },
    {
      id: "2",
      title: "Links, images, lists",
      summary: "Connect pages and group items.",
      clash: {
        name: "Broken Anchors",
        blurb: "Every link 404s. Restore href.",
      },
      lessons: [
        {
          id: "1",
          title: "Links",
          minutes: 3,
          teach: {
            title: "a plus href",
            body: '<a href="url">label</a> is a link. href is the destination. The words between the tags are what the visitor clicks. Use relative paths for your own pages, full URLs for other sites.',
            code: '<a href="https://example.com">Example</a>',
          },
          terms: [
            { term: "<a>", def: "Anchor — a hyperlink" },
            { term: "href", def: "The URL the link points to" },
          ],
          questions: [
            {
              id: "html-2-1-a",
              kind: "fill",
              prompt: "Point the link at /learn.",
              code: '<a ___="/learn">Learn</a>',
              choices: ["href", "src", "link", "to"],
              answer: "href",
              why: "Anchors use href. Images use src.",
              concept: "links",
            },
            {
              id: "html-2-1-b",
              kind: "choice",
              prompt: "Which is a complete link?",
              choices: [
                '<a href="/you">You</a>',
                "<a>/you</a>",
                '<link href="/you">You</link>',
                '<a src="/you">You</a>',
              ],
              answer: 0,
              why: "a + href + clickable text.",
              concept: "links",
            },
            {
              id: "html-2-1-c",
              kind: "bool",
              prompt: "The visible click text is the href.",
              answer: false,
              why: "href is the destination. The content inside <a> is the label.",
              concept: "links",
            },
          ],
        },
        {
          id: "2",
          title: "Images",
          minutes: 3,
          teach: {
            title: "img is a void element",
            body: '<img src="photo.jpg" alt="A lake at dusk"> has no closer. src is the file. alt describes the image for screen readers and for when the file fails to load. Always write alt.',
            code: '<img src="lake.jpg" alt="Still lake at dusk">',
          },
          terms: [
            { term: "src", def: "Path or URL of the image file" },
            { term: "alt", def: "Text replacement for the image" },
          ],
          questions: [
            {
              id: "html-2-2-a",
              kind: "fill",
              prompt: "Describe the image.",
              code: '<img src="cat.jpg" ___="A sleeping cat">',
              choices: ["alt", "href", "title", "desc"],
              answer: "alt",
              why: "alt is the accessible description.",
              concept: "images",
            },
            {
              id: "html-2-2-b",
              kind: "choice",
              prompt: "Which attribute points at the file?",
              choices: ["src", "href", "url", "file"],
              answer: 0,
              why: "Embedded resources (img, script, audio) use src.",
              concept: "images",
            },
            {
              id: "html-2-2-c",
              kind: "bool",
              prompt: "<img> needs a closing </img> tag.",
              answer: false,
              why: "img is void — no closer. Put everything in the opener.",
              concept: "images",
            },
          ],
        },
        {
          id: "3",
          title: "Lists",
          minutes: 3,
          teach: {
            title: "ul, ol, li",
            body: "ul is bullets. ol is numbers. Each item is li. Nest the li elements inside the list — don't leave them as siblings.",
            code: "<ul>\n  <li>Python</li>\n  <li>CSS</li>\n</ul>",
          },
          terms: [
            { term: "<ul>", def: "Unordered (bulleted) list" },
            { term: "<ol>", def: "Ordered (numbered) list" },
            { term: "<li>", def: "One list item" },
          ],
          questions: [
            {
              id: "html-2-3-a",
              kind: "choice",
              prompt: "Which list is numbered?",
              choices: ["<ol>", "<ul>", "<li>", "<dl>"],
              answer: 0,
              why: "ol = ordered list.",
              concept: "lists",
            },
            {
              id: "html-2-3-b",
              kind: "fill",
              prompt: "Add an item.",
              code: "<ul>\n  <___>Java</li>\n</ul>",
              choices: ["li", "item", "ul", "p"],
              answer: "li",
              why: "Every item is an li, inside ul or ol.",
              concept: "lists",
            },
            {
              id: "html-2-3-c",
              kind: "order",
              prompt: "Build a two-item list.",
              choices: ["<ul>", "<li>A</li>", "<li>B</li>", "</ul>"],
              why: "Open the list, add items, then close it.",
              concept: "lists",
            },
          ],
        },
      ],
    },
    {
      id: "3",
      title: "Structure and forms",
      summary: "div, span, and inputs.",
      clash: {
        name: "Formless Form",
        blurb: "Inputs collect nothing. Restore name and type.",
      },
      lessons: [
        {
          id: "1",
          title: "div and span",
          minutes: 3,
          teach: {
            title: "Generic boxes",
            body: "div is a block box for grouping. span is an inline box for a slice of text. They mean nothing by themselves — you add class or id and style them with CSS. Prefer real tags (header, nav, main) when they fit.",
            code: '<div class="card">\n  <span class="muted">Lesson</span>\n  <p>print()</p>\n</div>',
          },
          terms: [
            { term: "<div>", def: "Generic block container" },
            { term: "<span>", def: "Generic inline container" },
          ],
          questions: [
            {
              id: "html-3-1-a",
              kind: "choice",
              prompt: "Which is inline by default?",
              choices: ["<span>", "<div>", "<p>", "<h1>"],
              answer: 0,
              why: "span sits in the text flow. div starts a new block.",
              concept: "div-span",
            },
            {
              id: "html-3-1-b",
              kind: "fill",
              prompt: "Group a card as a block.",
              code: "<___ class=\"card\">...</div>",
              choices: ["div", "span", "block", "box"],
              answer: "div",
              why: "Cards and layout groups are usually div (or a semantic tag).",
              concept: "div-span",
            },
            {
              id: "html-3-1-c",
              kind: "bool",
              prompt: "A div has built-in meaning for screen readers.",
              answer: false,
              why: "div is meaningless. Use header, nav, button, etc. when you can.",
              concept: "div-span",
            },
          ],
        },
        {
          id: "2",
          title: "Inputs",
          minutes: 3,
          teach: {
            title: "Forms collect data",
            body: '<input> is void. type picks the control: text, email, password, checkbox, number. name is the key sent to the server. A <label> tied with for/id makes the field usable.',
            code: '<label for="email">Email</label>\n<input id="email" type="email" name="email">',
          },
          terms: [
            { term: "type", def: "The kind of input control" },
            { term: "name", def: "Key used when the form is submitted" },
          ],
          questions: [
            {
              id: "html-3-2-a",
              kind: "fill",
              prompt: "Make a password field.",
              code: '<input type="___">',
              choices: ["password", "text", "secret", "hidden"],
              answer: "password",
              why: "type='password' masks the characters.",
              concept: "forms",
            },
            {
              id: "html-3-2-b",
              kind: "choice",
              prompt: "Which attribute is the submit key?",
              choices: ["name", "id", "class", "value"],
              answer: 0,
              why: "The server reads name=value pairs. id is for labels and CSS.",
              concept: "forms",
            },
            {
              id: "html-3-2-c",
              kind: "bool",
              prompt: "Every input should have a label.",
              answer: true,
              why: "Labels name the field for everyone, including keyboard and screen-reader users.",
              concept: "forms",
            },
          ],
        },
        {
          id: "3",
          title: "Buttons and submit",
          minutes: 3,
          teach: {
            title: "button vs input",
            body: '<button type="submit">Save</button> inside a form sends it. type="button" does not submit — use that for actions you handle with JavaScript. A bare <button> inside a form defaults to submit, which surprises people.',
            code: "<form>\n  <button type=\"submit\">Save</button>\n  <button type=\"button\">Preview</button>\n</form>",
          },
          terms: [
            { term: "submit", def: "Send the form" },
            { term: "<form>", def: "Wraps fields that go together" },
          ],
          questions: [
            {
              id: "html-3-3-a",
              kind: "fill",
              prompt: "This button should send the form.",
              code: '<button type="___">Save</button>',
              choices: ["submit", "button", "send", "save"],
              answer: "submit",
              why: "type='submit' sends the enclosing form.",
              concept: "buttons",
            },
            {
              id: "html-3-3-b",
              kind: "choice",
              prompt: "A JS-only action should use",
              choices: ['type="button"', 'type="submit"', "<input type='js'>", "<a>"],
              answer: 0,
              why: "type='button' does not submit. That keeps the page from reloading.",
              concept: "buttons",
            },
            {
              id: "html-3-3-c",
              kind: "bool",
              prompt: "A <button> inside a form defaults to submit.",
              answer: true,
              why: "Always set type explicitly so the default does not bite you.",
              concept: "buttons",
            },
          ],
        },
      ],
    },
  ],
};
