import type { Track } from "./types";

export const javascript: Track = {
  id: "javascript",
  name: "JavaScript",
  short: "JS",
  blurb: "The language of the web. Every button, every page.",
  level: "Beginner",
  chapters: [
    {
      id: "1",
      title: "Talk to the browser",
      summary: "Log values, leave notes, and declare names.",
      clash: {
        name: "Muted Console",
        blurb: "console.log is silent. Restore the voice of the page.",
      },
      lessons: [
        {
          id: "1",
          title: "console.log",
          minutes: 3,
          teach: {
            title: "The console is your scratchpad",
            body: "JavaScript in the browser speaks through console.log(). Open DevTools to see it. Semicolons are optional but common. Strings need quotes.",
            code: 'console.log("Hello, Synapse");',
          },
          terms: [
            { term: "console.log()", def: "Prints a value to the browser console" },
            { term: "statement", def: "A single instruction, often ending with ;" },
          ],
          questions: [
            {
              id: "js-1-1-a",
              kind: "fill",
              prompt: "Write Hello to the console.",
              code: 'console.___("Hello");',
              choices: ["log", "print", "write", "echo"],
              answer: "log",
              why: "The method is log on the console object. print is Python.",
              concept: "console",
            },
            {
              id: "js-1-1-b",
              kind: "choice",
              prompt: "Which line is valid JavaScript?",
              choices: [
                'console.log("Hi");',
                'print("Hi");',
                "console.log(Hi);",
                "echo Hi;",
              ],
              answer: 0,
              why: "JS uses console.log and quoted strings.",
              concept: "console",
            },
            {
              id: "js-1-1-c",
              kind: "bool",
              prompt: "console.log is Python's print by another name.",
              answer: true,
              why: "Same job, different language: show a value for humans to read.",
              concept: "console",
            },
          ],
        },
        {
          id: "2",
          title: "Comments",
          minutes: 2,
          teach: {
            title: "Two ways to comment",
            body: "// comments out the rest of a line. /* */ wraps a block. The engine ignores both.",
            code: '// one line\n/* several\n   lines */',
          },
          terms: [{ term: "//", def: "Line comment in JavaScript" }],
          questions: [
            {
              id: "js-1-2-a",
              kind: "choice",
              prompt: "Which starts a single-line JS comment?",
              choices: ["//", "#", "--", "<!--"],
              answer: 0,
              why: "// is JavaScript (and Java, TS). # is Python.",
              concept: "js-comments",
            },
            {
              id: "js-1-2-b",
              kind: "bool",
              prompt: "This still logs Hi.",
              code: '// console.log("Hi");',
              answer: false,
              why: "The call is commented out, so it never runs.",
              concept: "js-comments",
            },
            {
              id: "js-1-2-c",
              kind: "fill",
              prompt: "Comment this line.",
              code: '___ const x = 1;',
              choices: ["//", "#", "--", "/*"],
              answer: "//",
              why: "// is the line comment. /* would need a closing */.",
              concept: "js-comments",
            },
          ],
        },
        {
          id: "3",
          title: "let and const",
          minutes: 4,
          teach: {
            title: "Declare before you use",
            body: "let makes a name you can reassign. const makes a name that cannot be reassigned. Prefer const unless the value must change. Use camelCase: totalScore.",
            code: 'const city = "Oslo";\nlet score = 0;\nscore = 10;',
            note: "Avoid var in new code. It is older and more surprising.",
          },
          terms: [
            { term: "const", def: "A name that cannot be reassigned" },
            { term: "let", def: "A name you can reassign" },
          ],
          questions: [
            {
              id: "js-1-3-a",
              kind: "choice",
              prompt: "Which name cannot be reassigned?",
              choices: ["const city = 'Oslo'", "let city = 'Oslo'", "var city = 'Oslo'", "city = 'Oslo'"],
              answer: 0,
              why: "const forbids city = somethingElse later.",
              concept: "declarations",
            },
            {
              id: "js-1-3-b",
              kind: "fill",
              prompt: "Declare a score you will update.",
              code: "___ score = 0;",
              choices: ["let", "const", "def", "int"],
              answer: "let",
              why: "Updating needs let (or var). const would throw.",
              concept: "declarations",
            },
            {
              id: "js-1-3-c",
              kind: "bool",
              prompt: "This is legal.",
              code: "const n = 1;\nn = 2;",
              answer: false,
              why: "Reassigning a const throws TypeError.",
              concept: "declarations",
            },
          ],
        },
      ],
    },
    {
      id: "2",
      title: "Values and operators",
      summary: "Types, math, and equality quirks.",
      clash: {
        name: "The Double Equal",
        blurb: "Loose equality is lying. Pin down ===.",
      },
      lessons: [
        {
          id: "1",
          title: "Primitive types",
          minutes: 3,
          teach: {
            title: "JS has a small set of primitives",
            body: "string, number, boolean, undefined, null, bigint, symbol. typeof reports most of them. There is no separate int and float — 3 and 3.14 are both number.",
            code: 'typeof "hi"  // "string"\ntypeof 4     // "number"\ntypeof true  // "boolean"',
          },
          terms: [
            { term: "typeof", def: "Operator that returns a type name string" },
            { term: "number", def: "JS numeric type — integers and decimals" },
          ],
          questions: [
            {
              id: "js-2-1-a",
              kind: "choice",
              prompt: 'What is typeof 4?',
              choices: ['"number"', '"int"', '"float"', '"Number"'],
              answer: 0,
              why: "JavaScript has one numeric primitive: number.",
              concept: "js-types",
            },
            {
              id: "js-2-1-b",
              kind: "fill",
              prompt: "Ask for the type of value.",
              code: "___ value",
              choices: ["typeof", "type", "typeOf", "class"],
              answer: "typeof",
              why: "typeof is an operator, written in lowercase.",
              concept: "js-types",
            },
            {
              id: "js-2-1-c",
              kind: "bool",
              prompt: "typeof null is 'null'.",
              answer: false,
              why: "A famous quirk: typeof null is 'object'. Remember it; don't rely on it.",
              concept: "js-types",
            },
          ],
        },
        {
          id: "2",
          title: "Math in JS",
          minutes: 3,
          teach: {
            title: "Operators look familiar",
            body: "+ - * / % ** work like most languages. + also concatenates strings. If either side is a string, + glues rather than adds. Number() or parseInt() convert text to a number.",
            code: 'console.log(2 + 3);\nconsole.log("2" + 3);\nconsole.log(Number("2") + 3);',
          },
          terms: [
            { term: "concatenation", def: "Gluing strings with +" },
            { term: "Number()", def: "Convert a value to a number" },
          ],
          questions: [
            {
              id: "js-2-2-a",
              kind: "choice",
              prompt: 'What is "2" + 3?',
              choices: ['"23"', "5", "6", "Error"],
              answer: 0,
              why: "+ with a string concatenates, so 3 becomes '3'.",
              concept: "js-operators",
            },
            {
              id: "js-2-2-b",
              kind: "choice",
              prompt: "What is 7 % 3?",
              choices: ["1", "2", "0", "3"],
              answer: 0,
              why: "7 = 2×3 + 1, remainder 1.",
              concept: "js-operators",
            },
            {
              id: "js-2-2-c",
              kind: "fill",
              prompt: "Turn the string into a number, then add 1.",
              code: '___("4") + 1',
              choices: ["Number", "int", "str", "parse"],
              answer: "Number",
              why: "Number('4') is 4, plus 1 is 5.",
              concept: "js-operators",
            },
          ],
        },
        {
          id: "3",
          title: "=== vs ==",
          minutes: 3,
          teach: {
            title: "Prefer strict equality",
            body: "=== checks value and type. == coerces types first, which hides bugs ('5' == 5 is true). Always write === and !== unless you have a precise reason not to.",
            code: '5 === "5"  // false\n5 == "5"   // true\n5 !== "5"  // true',
          },
          terms: [
            { term: "===", def: "Strict equality — value and type" },
            { term: "==", def: "Loose equality — coerces types" },
          ],
          questions: [
            {
              id: "js-2-3-a",
              kind: "choice",
              prompt: 'What is 5 === "5"?',
              choices: ["false", "true", "5", "Error"],
              answer: 0,
              why: "number 5 and string '5' are different types.",
              concept: "equality",
            },
            {
              id: "js-2-3-b",
              kind: "fill",
              prompt: "Strictly compare a and b.",
              code: "a ___ b",
              choices: ["===", "==", "=", "!=="],
              answer: "===",
              why: "=== is the comparison you want in almost every if.",
              concept: "equality",
            },
            {
              id: "js-2-3-c",
              kind: "bool",
              prompt: "== is safer than ===.",
              answer: false,
              why: "Loose equality coerces silently. Strict is the safe default.",
              concept: "equality",
            },
          ],
        },
      ],
    },
    {
      id: "3",
      title: "Functions and forks",
      summary: "Reusable blocks and if statements.",
      clash: {
        name: "The Hollow Function",
        blurb: "Calls go in. Nothing comes out. Restore return.",
      },
      lessons: [
        {
          id: "1",
          title: "Write a function",
          minutes: 4,
          teach: {
            title: "Functions package work",
            body: "function name(params) { ... } declares a function. return hands a value back. If you skip return, the result is undefined. Call it with name().",
            code: "function add(a, b) {\n  return a + b;\n}\nconsole.log(add(2, 3));",
          },
          terms: [
            { term: "function", def: "A named, reusable block of code" },
            { term: "return", def: "Sends a value back to the caller" },
            { term: "parameter", def: "A name for an input, like a or b" },
          ],
          questions: [
            {
              id: "js-3-1-a",
              kind: "fill",
              prompt: "Send the sum back to the caller.",
              code: "function add(a, b) {\n  ___ a + b;\n}",
              choices: ["return", "print", "yield", "send"],
              answer: "return",
              why: "return is how a function gives a value back.",
              concept: "functions",
            },
            {
              id: "js-3-1-b",
              kind: "choice",
              prompt: "How do you run greet?",
              choices: ["greet()", "greet", "call greet", "run(greet)"],
              answer: 0,
              why: "Parentheses call. Without them you just mention the function.",
              concept: "functions",
            },
            {
              id: "js-3-1-c",
              kind: "order",
              prompt: "Declare double, then use it.",
              choices: [
                "function double(n) { return n * 2; }",
                "console.log(double(4));",
              ],
              why: "A function declaration can be called after it exists in the file.",
              concept: "functions",
            },
          ],
        },
        {
          id: "2",
          title: "if / else",
          minutes: 3,
          teach: {
            title: "Braces wrap the branch",
            body: "if (condition) { ... } else { ... }. The condition sits in parentheses. Curly braces wrap the body. else if chains extra tests.",
            code: 'const score = 80;\nif (score >= 70) {\n  console.log("pass");\n} else {\n  console.log("retry");\n}',
          },
          terms: [
            { term: "if", def: "Run a block when a condition is true" },
            { term: "else", def: "The path when the if is false" },
          ],
          questions: [
            {
              id: "js-3-2-a",
              kind: "fill",
              prompt: "Start a condition.",
              code: "___ (ready) {\n  go();\n}",
              choices: ["if", "when", "elif", "int"],
              answer: "if",
              why: "JS uses if, with the condition in parentheses.",
              concept: "js-if",
            },
            {
              id: "js-3-2-b",
              kind: "choice",
              prompt: "What does this log?",
              code: "const n = 2;\nif (n > 5) {\n  console.log('big');\n} else {\n  console.log('small');\n}",
              choices: ["small", "big", "2", "nothing"],
              answer: 0,
              why: "2 is not greater than 5, so else runs.",
              concept: "js-if",
            },
            {
              id: "js-3-2-c",
              kind: "bool",
              prompt: "JS if-conditions must be in parentheses.",
              answer: true,
              why: "if ready { is a syntax error. if (ready) { is correct.",
              concept: "js-if",
            },
          ],
        },
        {
          id: "3",
          title: "Arrays in brief",
          minutes: 3,
          teach: {
            title: "Lists with square brackets",
            body: "An array holds values in order. ['a', 'b'][0] is 'a'. .length is the count. .push() adds to the end.",
            code: 'const langs = ["js", "py"];\nlangs.push("sql");\nconsole.log(langs.length);',
          },
          terms: [
            { term: "array", def: "An ordered list of values" },
            { term: ".push()", def: "Add an item to the end of an array" },
          ],
          questions: [
            {
              id: "js-3-3-a",
              kind: "choice",
              prompt: "What is ['a','b'][0]?",
              choices: ["'a'", "'b'", "0", "2"],
              answer: 0,
              why: "Index 0 is the first item.",
              concept: "arrays",
            },
            {
              id: "js-3-3-b",
              kind: "fill",
              prompt: "Add 'sql' to langs.",
              code: 'langs.___("sql");',
              choices: ["push", "add", "append", "put"],
              answer: "push",
              why: "Array.prototype.push adds to the end.",
              concept: "arrays",
            },
            {
              id: "js-3-3-c",
              kind: "bool",
              prompt: "['a','b'].length is 2.",
              answer: true,
              why: "length counts items, not the last index.",
              concept: "arrays",
            },
          ],
        },
      ],
    },
  ],
};
