import type { Track } from "./types";

export const java: Track = {
  id: "java",
  name: "Java",
  short: "Ja",
  blurb: "Strict, portable, everywhere — apps, Android, servers.",
  level: "Beginner",
  chapters: [
    {
      id: "1",
      title: "A running class",
      summary: "The main method, printing, comments.",
      clash: {
        name: "No Entry Point",
        blurb: "The JVM cannot find main. Restore the signature.",
      },
      lessons: [
        {
          id: "1",
          title: "public class and main",
          minutes: 4,
          teach: {
            title: "Java programs live in classes",
            body: "The JVM starts at public static void main(String[] args). The file name must match the public class name. Braces wrap every block. Statements end with semicolons.",
            code: "public class Hello {\n  public static void main(String[] args) {\n    System.out.println(\"Hello\");\n  }\n}",
          },
          terms: [
            { term: "main", def: "The method the JVM calls to start the program" },
            { term: "class", def: "A blueprint that holds methods and data" },
          ],
          questions: [
            {
              id: "ja-1-1-a",
              kind: "fill",
              prompt: "The JVM starts here.",
              code: "public static void ___(String[] args) { }",
              choices: ["main", "start", "run", "init"],
              answer: "main",
              why: "The entry point is always named main with that signature.",
              concept: "main",
            },
            {
              id: "ja-1-1-b",
              kind: "choice",
              prompt: "A public class Hello should live in",
              choices: ["Hello.java", "hello.java", "Main.java", "hello.class"],
              answer: 0,
              why: "The file name matches the public class, including case.",
              concept: "main",
            },
            {
              id: "ja-1-1-c",
              kind: "bool",
              prompt: "Java statements end with a semicolon.",
              answer: true,
              why: "Missing semicolons are a compile error.",
              concept: "main",
            },
          ],
        },
        {
          id: "2",
          title: "System.out.println",
          minutes: 3,
          teach: {
            title: "Print a line",
            body: "System.out.println(value) writes a line to the console. print writes without a newline. Strings use double quotes — Java does not accept single quotes for strings (those are chars).",
            code: "System.out.println(\"Hello, Synapse\");",
          },
          terms: [
            { term: "System.out.println", def: "Print a value and end the line" },
            { term: "String", def: "Text in double quotes" },
          ],
          questions: [
            {
              id: "ja-1-2-a",
              kind: "fill",
              prompt: "Print a line of text.",
              code: "System.out.___(\"Hi\");",
              choices: ["println", "log", "printLine", "echo"],
              answer: "println",
              why: "println is the standard line printer.",
              concept: "println",
            },
            {
              id: "ja-1-2-b",
              kind: "choice",
              prompt: "Which string is legal Java?",
              choices: ['"Hi"', "'Hi'", "`Hi`", "Hi"],
              answer: 0,
              why: "Double quotes for String. Single quotes are for a single char.",
              concept: "println",
            },
            {
              id: "ja-1-2-c",
              kind: "bool",
              prompt: "print and println both add a newline.",
              answer: false,
              why: "Only println advances to the next line.",
              concept: "println",
            },
          ],
        },
        {
          id: "3",
          title: "Comments",
          minutes: 2,
          teach: {
            title: "Same family as JS",
            body: "// line comment. /* block */. /** javadoc */ for methods and classes the docs tool can read.",
            code: "// greeting\nSystem.out.println(\"Hi\");",
          },
          terms: [{ term: "//", def: "Line comment" }],
          questions: [
            {
              id: "ja-1-3-a",
              kind: "choice",
              prompt: "A Java line comment starts with",
              choices: ["//", "#", "--", "<!--"],
              answer: 0,
              why: "Java shares // with JS and C.",
              concept: "java-comments",
            },
            {
              id: "ja-1-3-b",
              kind: "bool",
              prompt: "This still prints Hi.",
              code: '// System.out.println("Hi");',
              answer: false,
              why: "The call is commented out.",
              concept: "java-comments",
            },
            {
              id: "ja-1-3-c",
              kind: "fill",
              prompt: "Comment the rest of the line.",
              code: "___ int x = 1;",
              choices: ["//", "#", "--", "rem"],
              answer: "//",
              why: "// comments to the end of the line.",
              concept: "java-comments",
            },
          ],
        },
      ],
    },
    {
      id: "2",
      title: "Types you declare",
      summary: "int, double, boolean, String.",
      clash: {
        name: "Type Mismatch",
        blurb: "The compiler refused every assignment. Name the types.",
      },
      lessons: [
        {
          id: "1",
          title: "Declare with a type",
          minutes: 4,
          teach: {
            title: "type name = value;",
            body: "Java is statically typed. You name the type: int count = 3; double price = 9.5; boolean ready = true; String city = \"Oslo\";. The compiler catches mismatches before the program runs.",
            code: "int lives = 3;\ndouble score = 12.5;\nboolean ready = true;\nString name = \"Ada\";",
          },
          terms: [
            { term: "int", def: "Whole number" },
            { term: "double", def: "Floating-point number" },
            { term: "boolean", def: "true or false" },
            { term: "String", def: "Text — a class, not a primitive" },
          ],
          questions: [
            {
              id: "ja-2-1-a",
              kind: "fill",
              prompt: "Declare a whole number.",
              code: "___ count = 3;",
              choices: ["int", "integer", "num", "let"],
              answer: "int",
              why: "int is the default integer type.",
              concept: "java-types",
            },
            {
              id: "ja-2-1-b",
              kind: "choice",
              prompt: "Which type stores true/false?",
              choices: ["boolean", "bool", "Boolean only", "bit"],
              answer: 0,
              why: "The primitive is boolean. Boolean is the wrapper class.",
              concept: "java-types",
            },
            {
              id: "ja-2-1-c",
              kind: "bool",
              prompt: "This compiles: int x = 1.5;",
              answer: false,
              why: "1.5 is a double. Assigning it to int needs a cast and truncates.",
              concept: "java-types",
            },
          ],
        },
        {
          id: "2",
          title: "final and naming",
          minutes: 3,
          teach: {
            title: "final cannot be reassigned",
            body: "final int MAX = 3; is a constant. Java uses camelCase for variables and methods, PascalCase for classes. Names are case-sensitive: Score and score are different.",
            code: "final int MAX_LIVES = 3;\nint currentLives = MAX_LIVES;",
          },
          terms: [
            { term: "final", def: "Cannot be reassigned after the first value" },
            { term: "camelCase", def: "currentLives — Java variable style" },
          ],
          questions: [
            {
              id: "ja-2-2-a",
              kind: "fill",
              prompt: "Make this a constant.",
              code: "___ int MAX = 3;",
              choices: ["final", "const", "static", "let"],
              answer: "final",
              why: "Java's const-like keyword is final. const is JS.",
              concept: "final",
            },
            {
              id: "ja-2-2-b",
              kind: "choice",
              prompt: "The usual name for a Java class is",
              choices: ["HelloWorld", "helloWorld", "hello_world", "HELLO_WORLD"],
              answer: 0,
              why: "Classes are PascalCase. Constants are UPPER_SNAKE.",
              concept: "final",
            },
            {
              id: "ja-2-2-c",
              kind: "bool",
              prompt: "final int x = 1; x = 2; compiles.",
              answer: false,
              why: "final forbids reassignment.",
              concept: "final",
            },
          ],
        },
        {
          id: "3",
          title: "Operators",
          minutes: 3,
          teach: {
            title: "Math and comparison",
            body: "+ - * / % work on numbers. Integer division truncates: 10 / 3 is 3. == compares primitives. For String, use .equals() — == on objects asks if they are the same object.",
            code: "int n = 10 / 3;\nboolean ok = n == 3;\nboolean same = name.equals(\"Ada\");",
          },
          terms: [
            { term: ".equals()", def: "Compare string contents" },
            { term: "integer division", def: "10 / 3 is 3 when both are int" },
          ],
          questions: [
            {
              id: "ja-2-3-a",
              kind: "choice",
              prompt: "What is 10 / 3 with both sides int?",
              choices: ["3", "3.33", "1", "10"],
              answer: 0,
              why: "Integer division drops the fraction.",
              concept: "java-ops",
            },
            {
              id: "ja-2-3-b",
              kind: "fill",
              prompt: "Compare two strings by content.",
              code: "name.___(\"Ada\")",
              choices: ["equals", "==", "===", "eq"],
              answer: "equals",
              why: "== on String is often wrong. equals checks characters.",
              concept: "java-ops",
            },
            {
              id: "ja-2-3-c",
              kind: "bool",
              prompt: "Use == to compare String contents.",
              answer: false,
              why: "== compares references. equals compares text.",
              concept: "java-ops",
            },
          ],
        },
      ],
    },
    {
      id: "3",
      title: "Control and arrays",
      summary: "if, for, and a first array.",
      clash: {
        name: "Infinite For",
        blurb: "The loop never lands. Repair the header.",
      },
      lessons: [
        {
          id: "1",
          title: "if / else",
          minutes: 3,
          teach: {
            title: "Parentheses and braces",
            body: "if (condition) { ... } else { ... }. Conditions must be boolean — Java will not treat 0 as false. else if chains extra tests.",
            code: "if (score >= 70) {\n  System.out.println(\"pass\");\n} else {\n  System.out.println(\"retry\");\n}",
          },
          terms: [
            { term: "if", def: "Run a block when a boolean is true" },
          ],
          questions: [
            {
              id: "ja-3-1-a",
              kind: "fill",
              prompt: "Start a branch.",
              code: "___ (ready) {\n  go();\n}",
              choices: ["if", "when", "elif", "int"],
              answer: "if",
              why: "Java uses if with a boolean in parentheses.",
              concept: "java-if",
            },
            {
              id: "ja-3-1-b",
              kind: "bool",
              prompt: "if (1) compiles in Java.",
              answer: false,
              why: "The condition must be boolean, not a number.",
              concept: "java-if",
            },
            {
              id: "ja-3-1-c",
              kind: "choice",
              prompt: "What prints when n is 2?",
              code: "if (n > 5) {\n  System.out.println(\"big\");\n} else {\n  System.out.println(\"small\");\n}",
              choices: ["small", "big", "2", "nothing"],
              answer: 0,
              why: "2 is not greater than 5.",
              concept: "java-if",
            },
          ],
        },
        {
          id: "2",
          title: "for loops",
          minutes: 4,
          teach: {
            title: "for (start; test; step)",
            body: "for (int i = 0; i < 3; i++) runs with i = 0, 1, 2. The middle test stops the loop when it becomes false. i++ means i = i + 1. Braces wrap the body.",
            code: "for (int i = 0; i < 3; i++) {\n  System.out.println(i);\n}",
          },
          terms: [
            { term: "for", def: "A loop with init, condition, and step" },
            { term: "i++", def: "Add one to i after the body" },
          ],
          questions: [
            {
              id: "ja-3-2-a",
              kind: "choice",
              prompt: "How many times does i < 3 run from i = 0 with i++?",
              choices: ["3", "2", "4", "forever"],
              answer: 0,
              why: "i is 0, 1, 2 — three times. When i is 3 the test fails.",
              concept: "java-for",
            },
            {
              id: "ja-3-2-b",
              kind: "fill",
              prompt: "Advance i by one each round.",
              code: "for (int i = 0; i < 3; ___) { }",
              choices: ["i++", "i--", "i = 0", "i + 1"],
              answer: "i++",
              why: "The step is i++. i + 1 does not assign.",
              concept: "java-for",
            },
            {
              id: "ja-3-2-c",
              kind: "order",
              prompt: "Write a 0..2 loop header and body.",
              choices: ["for (int i = 0; i < 3; i++) {", "  System.out.println(i);", "}"],
              why: "Header, body, close brace.",
              concept: "java-for",
            },
          ],
        },
        {
          id: "3",
          title: "Arrays",
          minutes: 3,
          teach: {
            title: "Fixed-length lists",
            body: "int[] nums = {1, 2, 3};. Length is nums.length. Index from 0. Arrays cannot grow — use ArrayList when you need a flexible list.",
            code: "int[] nums = {1, 2, 3};\nSystem.out.println(nums[0]);\nSystem.out.println(nums.length);",
          },
          terms: [
            { term: "array", def: "A fixed-length sequence of one type" },
            { term: ".length", def: "How many slots the array has" },
          ],
          questions: [
            {
              id: "ja-3-3-a",
              kind: "choice",
              prompt: "What is nums[0] for {1, 2, 3}?",
              choices: ["1", "2", "0", "3"],
              answer: 0,
              why: "Index 0 is the first slot.",
              concept: "java-arrays",
            },
            {
              id: "ja-3-3-b",
              kind: "fill",
              prompt: "Read how many slots.",
              code: "nums.___",
              choices: ["length", "len", "size", "count"],
              answer: "length",
              why: "Arrays use length (a field). ArrayList uses size().",
              concept: "java-arrays",
            },
            {
              id: "ja-3-3-c",
              kind: "bool",
              prompt: "A Java array can grow with .push().",
              answer: false,
              why: "Length is fixed at creation. ArrayList is the growable type.",
              concept: "java-arrays",
            },
          ],
        },
      ],
    },
  ],
};
