import type { Track } from "./types";

export const python: Track = {
  id: "python",
  name: "Python",
  short: "Py",
  blurb: "Read like English. Used in data, AI, and the web.",
  level: "Beginner",
  chapters: [
    {
      id: "1",
      title: "First programs",
      summary: "Print text, leave notes, and store values.",
      clash: {
        name: "The Silent Console",
        blurb: "A glitch ate every print. Teach it to speak again.",
      },
      lessons: [
        {
          id: "1",
          title: "Say it with print",
          minutes: 3,
          teach: {
            title: "print() shows text",
            body: "Python runs from top to bottom. print() sends a message to the console — the place your program talks back to you. Wrap the message in quotes so Python treats it as text, not a command.",
            code: 'print("Hello, Synapse")',
            note: "Quotes can be single or double. Just close the same kind you opened.",
          },
          terms: [
            { term: "print()", def: "Shows a value in the console" },
            { term: "string", def: "Text wrapped in quotes" },
          ],
          questions: [
            {
              id: "py-1-1-a",
              kind: "fill",
              prompt: "Complete the line so it greets the console.",
              code: '___("Hello")',
              choices: ["print", "echo", "console", "say"],
              answer: "print",
              why: "Python uses print() to write to the console — not echo or console.log.",
              concept: "print",
            },
            {
              id: "py-1-1-b",
              kind: "choice",
              prompt: "Which line is valid Python?",
              choices: [
                'print("Ready")',
                "print(Ready)",
                "print Hello",
                'echo("Ready")',
              ],
              answer: 0,
              why: "The message needs quotes. Without them, Python looks for a variable named Ready.",
              concept: "print",
            },
            {
              id: "py-1-1-c",
              kind: "bool",
              prompt: "This prints Hello twice on the same line.",
              code: 'print("Hello")\nprint("Hello")',
              answer: false,
              why: "Each print() starts a new line by default, so you get two lines.",
              concept: "print",
            },
            {
              id: "py-1-1-d",
              kind: "code",
              prompt: "Write a program that prints exactly: Hello, world",
              expected: "Hello, world",
              requires: ["print"],
              why: "print(\"Hello, world\") sends the text to the console. The quotes are not part of the output.",
              concept: "print",
            },
          ],
        },
        {
          id: "2",
          title: "Notes to future you",
          minutes: 3,
          teach: {
            title: "Comments are ignored",
            body: "A hash (#) starts a comment. Python skips it. Use comments to explain why, not to narrate every line. They never change how the program runs.",
            code: '# Greet the learner\nprint("Hello")',
          },
          terms: [{ term: "comment", def: "A note Python ignores, starting with #" }],
          questions: [
            {
              id: "py-1-2-a",
              kind: "choice",
              prompt: "Which character starts a Python comment?",
              choices: ["#", "//", "/*", "--"],
              answer: 0,
              why: "Python comments start with #. // is JavaScript, -- is SQL.",
              concept: "comments",
            },
            {
              id: "py-1-2-b",
              kind: "bool",
              prompt: "This program prints Hi.",
              code: '# print("Hi")',
              answer: false,
              why: "The whole line is a comment, so print never runs.",
              concept: "comments",
            },
            {
              id: "py-1-2-c",
              kind: "fill",
              prompt: "Turn this into a comment.",
              code: '___ Keep this for later',
              choices: ["#", "//", "/*", "rem"],
              answer: "#",
              why: "Only # starts a comment in Python.",
              concept: "comments",
            },
          ],
        },
        {
          id: "3",
          title: "Named boxes",
          minutes: 4,
          teach: {
            title: "Variables store values",
            body: "A variable is a name that points at a value. Use = to assign. Names should describe the thing they hold. Python does not need a type keyword — the value decides the type.",
            code: 'name = "Ada"\nprint(name)',
            note: "Use snake_case: total_score, not totalScore.",
          },
          terms: [
            { term: "variable", def: "A name that holds a value" },
            { term: "assignment", def: "The = that stores a value in a name" },
          ],
          questions: [
            {
              id: "py-1-3-a",
              kind: "fill",
              prompt: "Store 7 in a variable called lives.",
              code: "lives ___ 7",
              choices: ["=", "==", ":", "->"],
              answer: "=",
              why: "One = assigns. Two == compare. Mixing them is a classic bug.",
              concept: "variables",
            },
            {
              id: "py-1-3-b",
              kind: "choice",
              prompt: "What does this print?",
              code: 'city = "Oslo"\nprint(city)',
              choices: ["Oslo", "city", '"Oslo"', "city = Oslo"],
              answer: 0,
              why: "print(city) shows the value in city, not the name.",
              concept: "variables",
            },
            {
              id: "py-1-3-c",
              kind: "order",
              prompt: "Store a score, then print it.",
              choices: ["score = 10", "print(score)"],
              why: "You must assign before you use the name, or Python raises NameError.",
              concept: "variables",
            },
            {
              id: "py-1-3-d",
              kind: "code",
              prompt: "Store 10 in a variable called score, then print it.",
              expected: "10",
              requires: ["score", "="],
              why: "score = 10 stores the value, and print(score) shows what is inside the name.",
              concept: "variables",
            },
          ],
        },
      ],
    },
    {
      id: "2",
      title: "Numbers that think",
      summary: "Math, types, and comparisons.",
      clash: {
        name: "Type Drift",
        blurb: "Integers and strings are colliding. Sort them out.",
      },
      lessons: [
        {
          id: "1",
          title: "Do the math",
          minutes: 3,
          teach: {
            title: "Operators compute",
            body: "+ - * / work as you'd expect. // is integer division (drops the fraction). % is remainder. ** is power. Parentheses change order, same as school math.",
            code: "print(7 + 3)\nprint(10 // 3)\nprint(2 ** 3)",
          },
          terms: [
            { term: "//", def: "Integer division — 10 // 3 is 3" },
            { term: "%", def: "Remainder — 10 % 3 is 1" },
          ],
          questions: [
            {
              id: "py-2-1-a",
              kind: "choice",
              prompt: "What is 10 // 3 in Python?",
              choices: ["3", "3.33", "1", "10"],
              answer: 0,
              why: "// keeps the whole number and throws away the decimal.",
              concept: "operators",
            },
            {
              id: "py-2-1-b",
              kind: "fill",
              prompt: "Get the remainder of 10 divided by 3.",
              code: "10 ___ 3",
              choices: ["%", "/", "//", "**"],
              answer: "%",
              why: "% is modulo — leftover after division.",
              concept: "operators",
            },
            {
              id: "py-2-1-c",
              kind: "bool",
              prompt: "2 ** 3 equals 6.",
              answer: false,
              why: "** is exponent: 2 ** 3 is 2×2×2 = 8. * would be 6.",
              concept: "operators",
            },
            {
              id: "py-2-1-d",
              kind: "code",
              prompt: "Print the remainder when 17 is divided by 5.",
              expected: "2",
              requires: ["%"],
              why: "17 % 5 is 2: 5 fits into 17 three times, with 2 left over.",
              concept: "operators",
            },
          ],
        },
        {
          id: "2",
          title: "What kind of value",
          minutes: 3,
          teach: {
            title: "Types describe values",
            body: "int is a whole number. float has a decimal. str is text. bool is True or False. type() tells you which one you have. You cannot add a number to a string until you convert.",
            code: 'print(type(4))\nprint(type(4.0))\nprint(int("12"))',
          },
          terms: [
            { term: "int", def: "A whole number, like 4" },
            { term: "float", def: "A number with a decimal, like 4.0" },
            { term: "str", def: "Text in quotes" },
          ],
          questions: [
            {
              id: "py-2-2-a",
              kind: "choice",
              prompt: "What is type(3.0)?",
              choices: ["float", "int", "str", "decimal"],
              answer: 0,
              why: "A decimal point makes it a float, even if the fraction is zero.",
              concept: "types",
            },
            {
              id: "py-2-2-b",
              kind: "fill",
              prompt: "Turn the text '8' into a number.",
              code: '___("8")',
              choices: ["int", "str", "num", "parse"],
              answer: "int",
              why: "int('8') converts a numeric string into an integer.",
              concept: "types",
            },
            {
              id: "py-2-2-c",
              kind: "bool",
              prompt: "This runs without error.",
              code: 'print(3 + "3")',
              answer: false,
              why: "Python refuses to add int and str. Convert one side first.",
              concept: "types",
            },
          ],
        },
        {
          id: "3",
          title: "True or not",
          minutes: 3,
          teach: {
            title: "Comparisons return bool",
            body: "== asks if two values are equal. != asks if they differ. < > <= >= compare order. The result is always True or False — a bool. That bool is what if statements later use.",
            code: "print(5 > 3)\nprint(2 == 2)\nprint(2 != 2)",
          },
          terms: [
            { term: "==", def: "Equal to" },
            { term: "!=", def: "Not equal to" },
            { term: "bool", def: "True or False" },
          ],
          questions: [
            {
              id: "py-2-3-a",
              kind: "choice",
              prompt: "What does 7 != 7 evaluate to?",
              choices: ["False", "True", "7", "Error"],
              answer: 0,
              why: "7 is equal to 7, so 'not equal' is False.",
              concept: "comparisons",
            },
            {
              id: "py-2-3-b",
              kind: "fill",
              prompt: "Check whether score equals 100.",
              code: "score ___ 100",
              choices: ["==", "=", "===", "is"],
              answer: "==",
              why: "== compares. = would assign 100 to score.",
              concept: "comparisons",
            },
            {
              id: "py-2-3-c",
              kind: "bool",
              prompt: "10 >= 10 is True.",
              answer: true,
              why: "Greater-or-equal includes the equal case.",
              concept: "comparisons",
            },
          ],
        },
      ],
    },
    {
      id: "3",
      title: "Words and forks",
      summary: "Strings, decisions, and combining conditions.",
      clash: {
        name: "The Forking Path",
        blurb: "Every branch leads nowhere. Rebuild the ifs.",
      },
      lessons: [
        {
          id: "1",
          title: "Working with text",
          minutes: 4,
          teach: {
            title: "Strings are sequences",
            body: "You can glue strings with +. len() counts characters. Index with [0] for the first character — Python counts from zero. Slices like [0:3] take a stretch.",
            code: 'word = "code"\nprint(len(word))\nprint(word[0])\nprint("hi " + "there")',
          },
          terms: [
            { term: "len()", def: "Number of items or characters" },
            { term: "index", def: "Position in a sequence, starting at 0" },
          ],
          questions: [
            {
              id: "py-3-1-a",
              kind: "choice",
              prompt: 'What is len("hi")?',
              choices: ["2", "1", "3", "0"],
              answer: 0,
              why: "h and i — two characters. Quotes are not counted.",
              concept: "strings",
            },
            {
              id: "py-3-1-b",
              kind: "fill",
              prompt: "Read the first character of name.",
              code: "name___",
              choices: ["[0]", "[1]", ".first", "(0)"],
              answer: "[0]",
              why: "Indexing starts at 0, so the first character is [0].",
              concept: "strings",
            },
            {
              id: "py-3-1-c",
              kind: "choice",
              prompt: "Which line concatenates two strings?",
              choices: [
                '"ab" + "c"',
                '"ab" - "c"',
                "concat(ab, c)",
                '"ab" ++ "c"',
              ],
              answer: 0,
              why: "Python concatenates with +.",
              concept: "strings",
            },
            {
              id: "py-3-1-d",
              kind: "code",
              prompt: "Use len() to print how many characters are in \"python\".",
              expected: "6",
              requires: ["len"],
              why: "len(\"python\") counts p-y-t-h-o-n, which is 6 characters.",
              concept: "strings",
            },
          ],
        },
        {
          id: "2",
          title: "If this, then that",
          minutes: 4,
          teach: {
            title: "if runs a block or skips it",
            body: "An if line ends with a colon. The indented block underneath runs only when the condition is True. else is the backup path. elif chains extra checks. Indentation is syntax in Python, not style.",
            code: "score = 80\nif score >= 70:\n    print(\"pass\")\nelse:\n    print(\"retry\")",
          },
          terms: [
            { term: "if", def: "Run a block when a condition is True" },
            { term: "else", def: "Run when the if was False" },
            { term: "indent", def: "Spaces that define a Python block" },
          ],
          questions: [
            {
              id: "py-3-2-a",
              kind: "order",
              prompt: "Print ok only if ready is True.",
              choices: ["if ready:", '    print("ok")'],
              why: "The colon ends the condition. The print must be indented under the if.",
              concept: "conditionals",
            },
            {
              id: "py-3-2-b",
              kind: "choice",
              prompt: "What does this print?",
              code: "n = 3\nif n > 5:\n    print(\"big\")\nelse:\n    print(\"small\")",
              choices: ["small", "big", "n", "nothing"],
              answer: 0,
              why: "3 is not greater than 5, so the else branch runs.",
              concept: "conditionals",
            },
            {
              id: "py-3-2-c",
              kind: "fill",
              prompt: "Add the backup branch.",
              code: "if ok:\n    print(1)\n___:\n    print(0)",
              choices: ["else", "elif", "otherwise", "then"],
              answer: "else",
              why: "else runs when the if condition is False.",
              concept: "conditionals",
            },
            {
              id: "py-3-2-d",
              kind: "code",
              prompt: "This should print big, but it has a bug. Fix it.",
              starter: "n = 9\nif n > 5\n    print(\"big\")",
              expected: "big",
              requires: ["if"],
              why: "An if line must end with a colon. Without it Python raises a SyntaxError.",
              concept: "conditionals",
            },
          ],
        },
        {
          id: "3",
          title: "And, or, not",
          minutes: 3,
          teach: {
            title: "Combine conditions",
            body: "and is True only if both sides are True. or is True if at least one side is. not flips True to False. Use parentheses when a line has several checks so the meaning stays obvious.",
            code: "age = 20\nhas_id = True\nprint(age >= 18 and has_id)",
          },
          terms: [
            { term: "and", def: "True only if both sides are True" },
            { term: "or", def: "True if at least one side is True" },
            { term: "not", def: "Flips True and False" },
          ],
          questions: [
            {
              id: "py-3-3-a",
              kind: "choice",
              prompt: "True and False equals…",
              choices: ["False", "True", "None", "Error"],
              answer: 0,
              why: "and needs both sides True.",
              concept: "boolean-logic",
            },
            {
              id: "py-3-3-b",
              kind: "bool",
              prompt: "True or False is True.",
              answer: true,
              why: "or succeeds if either side is True.",
              concept: "boolean-logic",
            },
            {
              id: "py-3-3-c",
              kind: "fill",
              prompt: "Flip the boolean.",
              code: "___ ready",
              choices: ["not", "!", "no", "~"],
              answer: "not",
              why: "Python spells negation as not, not !.",
              concept: "boolean-logic",
            },
          ],
        },
      ],
    },
  ],
};
