import type { Track } from "./types";

export const sql: Track = {
  id: "sql",
  name: "SQL",
  short: "Sq",
  blurb: "Ask tables questions. The language of data.",
  level: "Beginner",
  chapters: [
    {
      id: "1",
      title: "Read a table",
      summary: "SELECT, FROM, columns.",
      clash: {
        name: "Empty Result",
        blurb: "Every query returns nothing. Restore SELECT.",
      },
      lessons: [
        {
          id: "1",
          title: "SELECT and FROM",
          minutes: 3,
          teach: {
            title: "Query = what + where-from",
            body: "SELECT chooses columns. FROM chooses the table. SQL is not case-sensitive for keywords, but the convention is uppercase keywords and lowercase names. End with a semicolon.",
            code: "SELECT name FROM users;",
          },
          terms: [
            { term: "SELECT", def: "Choose which columns to return" },
            { term: "FROM", def: "Choose which table to read" },
          ],
          questions: [
            {
              id: "sq-1-1-a",
              kind: "fill",
              prompt: "Read every column from users.",
              code: "___ * FROM users;",
              choices: ["SELECT", "GET", "FIND", "READ"],
              answer: "SELECT",
              why: "SELECT is how you read rows. There is no GET in SQL.",
              concept: "select",
            },
            {
              id: "sq-1-1-b",
              kind: "choice",
              prompt: "Which query is valid?",
              choices: [
                "SELECT name FROM users;",
                "GET name FROM users;",
                "SELECT name IN users;",
                "FROM users SELECT name;",
              ],
              answer: 0,
              why: "SELECT columns FROM table is the core shape.",
              concept: "select",
            },
            {
              id: "sq-1-1-c",
              kind: "bool",
              prompt: "* means every column.",
              answer: true,
              why: "SELECT * returns all columns. Prefer naming columns in real apps.",
              concept: "select",
            },
          ],
        },
        {
          id: "2",
          title: "Pick columns",
          minutes: 3,
          teach: {
            title: "Name what you need",
            body: "List columns with commas: SELECT name, email FROM users; Order in SELECT is the order in the result. Aliases rename a column in the output: SELECT name AS username.",
            code: "SELECT name, email FROM users;",
          },
          terms: [
            { term: "column", def: "A field, like name or email" },
            { term: "AS", def: "Rename a column in the result" },
          ],
          questions: [
            {
              id: "sq-1-2-a",
              kind: "fill",
              prompt: "Return name and city.",
              code: "SELECT name___ city FROM users;",
              choices: [",", "AND", "+", "with"],
              answer: ",",
              why: "Columns are a comma-separated list.",
              concept: "columns",
            },
            {
              id: "sq-1-2-b",
              kind: "choice",
              prompt: "Rename name to username.",
              choices: [
                "SELECT name AS username FROM users;",
                "SELECT name -> username FROM users;",
                "SELECT username = name FROM users;",
                "RENAME name TO username;",
              ],
              answer: 0,
              why: "AS aliases the output column.",
              concept: "columns",
            },
            {
              id: "sq-1-2-c",
              kind: "bool",
              prompt: "SELECT order does not matter.",
              answer: false,
              why: "The result columns appear in the order you list them.",
              concept: "columns",
            },
          ],
        },
        {
          id: "3",
          title: "DISTINCT and LIMIT",
          minutes: 3,
          teach: {
            title: "Unique rows, fewer rows",
            body: "SELECT DISTINCT city FROM users; drops duplicates. LIMIT 10 returns at most ten rows — useful while exploring. Some databases use TOP or FETCH instead of LIMIT.",
            code: "SELECT DISTINCT city FROM users LIMIT 10;",
          },
          terms: [
            { term: "DISTINCT", def: "Remove duplicate rows from the result" },
            { term: "LIMIT", def: "Cap how many rows come back" },
          ],
          questions: [
            {
              id: "sq-1-3-a",
              kind: "fill",
              prompt: "Return unique cities.",
              code: "SELECT ___ city FROM users;",
              choices: ["DISTINCT", "UNIQUE", "ONLY", "UNIQ"],
              answer: "DISTINCT",
              why: "DISTINCT is the keyword.",
              concept: "distinct",
            },
            {
              id: "sq-1-3-b",
              kind: "choice",
              prompt: "Get at most 5 rows.",
              choices: [
                "SELECT * FROM users LIMIT 5;",
                "SELECT * FROM users MAX 5;",
                "SELECT 5 FROM users;",
                "SELECT * FROM users WHERE 5;",
              ],
              answer: 0,
              why: "LIMIT 5 caps the result.",
              concept: "distinct",
            },
            {
              id: "sq-1-3-c",
              kind: "bool",
              prompt: "LIMIT changes data in the table.",
              answer: false,
              why: "SELECT never writes. LIMIT only trims the result set.",
              concept: "distinct",
            },
          ],
        },
      ],
    },
    {
      id: "2",
      title: "Filter and sort",
      summary: "WHERE, AND/OR, ORDER BY.",
      clash: {
        name: "Unfiltered Flood",
        blurb: "WHERE is missing. Millions of rows pour through.",
      },
      lessons: [
        {
          id: "1",
          title: "WHERE",
          minutes: 3,
          teach: {
            title: "Keep rows that match",
            body: "WHERE is a boolean test per row. = compares. Strings need quotes: WHERE city = 'Oslo'. Numbers do not. <> or != means not equal, depending on the dialect.",
            code: "SELECT name FROM users WHERE city = 'Oslo';",
          },
          terms: [
            { term: "WHERE", def: "Filter rows by a condition" },
          ],
          questions: [
            {
              id: "sq-2-1-a",
              kind: "fill",
              prompt: "Keep active users.",
              code: "SELECT * FROM users ___ active = TRUE;",
              choices: ["WHERE", "IF", "FILTER", "HAVING"],
              answer: "WHERE",
              why: "WHERE filters rows before grouping. HAVING is after GROUP BY.",
              concept: "where",
            },
            {
              id: "sq-2-1-b",
              kind: "choice",
              prompt: "Which filter is valid?",
              choices: [
                "WHERE city = 'Oslo'",
                "WHERE city = Oslo",
                "IF city = 'Oslo'",
                "WHERE city == 'Oslo'",
              ],
              answer: 0,
              why: "SQL uses = and quoted strings. == is a programming language.",
              concept: "where",
            },
            {
              id: "sq-2-1-c",
              kind: "bool",
              prompt: "WHERE city = Oslo works if Oslo is text.",
              answer: false,
              why: "Unquoted Oslo is treated as a column name.",
              concept: "where",
            },
          ],
        },
        {
          id: "2",
          title: "AND, OR, LIKE",
          minutes: 3,
          teach: {
            title: "Combine filters",
            body: "AND needs both tests. OR needs one. LIKE matches patterns: % is any stretch, _ is one character. WHERE name LIKE 'A%' finds names that start with A.",
            code: "SELECT * FROM users\nWHERE city = 'Oslo' AND active = TRUE;",
          },
          terms: [
            { term: "AND", def: "Both conditions must be true" },
            { term: "LIKE", def: "Pattern match on text" },
            { term: "%", def: "Wildcard for any number of characters" },
          ],
          questions: [
            {
              id: "sq-2-2-a",
              kind: "choice",
              prompt: "Names starting with A:",
              choices: [
                "WHERE name LIKE 'A%'",
                "WHERE name LIKE '%A'",
                "WHERE name = 'A%'",
                "WHERE name STARTS 'A'",
              ],
              answer: 0,
              why: "'A%' means A then anything. '%A' means anything then A.",
              concept: "like",
            },
            {
              id: "sq-2-2-b",
              kind: "fill",
              prompt: "Both filters must pass.",
              code: "WHERE city = 'Oslo' ___ active = TRUE",
              choices: ["AND", "OR", "PLUS", "WITH"],
              answer: "AND",
              why: "AND requires both sides true.",
              concept: "like",
            },
            {
              id: "sq-2-2-c",
              kind: "bool",
              prompt: "OR is true if either side is true.",
              answer: true,
              why: "Same meaning as in Python and JS.",
              concept: "like",
            },
          ],
        },
        {
          id: "3",
          title: "ORDER BY",
          minutes: 3,
          teach: {
            title: "Sort the result",
            body: "ORDER BY city sorts ascending (A–Z, small to large). ORDER BY created_at DESC puts newest first. You can sort by several columns: ORDER BY city, name.",
            code: "SELECT name, city FROM users\nORDER BY city ASC, name ASC;",
          },
          terms: [
            { term: "ORDER BY", def: "Sort the result rows" },
            { term: "DESC", def: "Descending sort — large to small" },
          ],
          questions: [
            {
              id: "sq-2-3-a",
              kind: "fill",
              prompt: "Newest first.",
              code: "ORDER BY created_at ___",
              choices: ["DESC", "ASC", "REV", "DOWN"],
              answer: "DESC",
              why: "DESC is descending. ASC is the default.",
              concept: "order",
            },
            {
              id: "sq-2-3-b",
              kind: "choice",
              prompt: "Which clause sorts?",
              choices: ["ORDER BY", "SORT BY", "ARRANGE", "GROUP BY"],
              answer: 0,
              why: "ORDER BY sorts. GROUP BY aggregates.",
              concept: "order",
            },
            {
              id: "sq-2-3-c",
              kind: "order",
              prompt: "Typical query order.",
              choices: [
                "SELECT name FROM users",
                "WHERE city = 'Oslo'",
                "ORDER BY name;",
              ],
              why: "SELECT/FROM, then WHERE, then ORDER BY.",
              concept: "order",
            },
          ],
        },
      ],
    },
    {
      id: "3",
      title: "More than one table",
      summary: "JOIN, COUNT, GROUP BY.",
      clash: {
        name: "Cartesian Storm",
        blurb: "A join without ON multiplied every row. Pin the keys.",
      },
      lessons: [
        {
          id: "1",
          title: "INNER JOIN",
          minutes: 4,
          teach: {
            title: "Rows that match on a key",
            body: "JOIN combines tables. INNER JOIN keeps rows with a match on both sides. ON spells the relationship: users.id = posts.user_id. Always write ON — a missing one produces a combinatorial explosion.",
            code: "SELECT users.name, posts.title\nFROM users\nINNER JOIN posts ON posts.user_id = users.id;",
          },
          terms: [
            { term: "JOIN", def: "Combine rows from two tables" },
            { term: "ON", def: "The match condition for a join" },
          ],
          questions: [
            {
              id: "sq-3-1-a",
              kind: "fill",
              prompt: "Spell the relationship.",
              code: "FROM users JOIN posts ___ posts.user_id = users.id",
              choices: ["ON", "WHERE", "AND", "USING"],
              answer: "ON",
              why: "ON is the join condition. WHERE can filter after.",
              concept: "join",
            },
            {
              id: "sq-3-1-b",
              kind: "choice",
              prompt: "INNER JOIN keeps",
              choices: [
                "rows with a match in both tables",
                "every row from the left table",
                "every possible pairing",
                "only unmatched rows",
              ],
              answer: 0,
              why: "Inner = intersection on the key.",
              concept: "join",
            },
            {
              id: "sq-3-1-c",
              kind: "bool",
              prompt: "A JOIN without ON is usually what you want.",
              answer: false,
              why: "That is a cross join — every row paired with every row.",
              concept: "join",
            },
          ],
        },
        {
          id: "2",
          title: "LEFT JOIN",
          minutes: 3,
          teach: {
            title: "Keep the left, even unmatched",
            body: "LEFT JOIN keeps every row from the left table. If the right side has no match, its columns are NULL. Use it for 'all users, and their posts if any'.",
            code: "SELECT users.name, posts.title\nFROM users\nLEFT JOIN posts ON posts.user_id = users.id;",
          },
          terms: [
            { term: "LEFT JOIN", def: "All left rows, matched right rows or NULL" },
            { term: "NULL", def: "SQL's missing value" },
          ],
          questions: [
            {
              id: "sq-3-2-a",
              kind: "choice",
              prompt: "A user with no posts in a LEFT JOIN appears",
              choices: [
                "once, with NULL post columns",
                "not at all",
                "once per post in the table",
                "as an error",
              ],
              answer: 0,
              why: "Left rows always survive. Unmatched right side is NULL.",
              concept: "left-join",
            },
            {
              id: "sq-3-2-b",
              kind: "fill",
              prompt: "Keep all users even without posts.",
              code: "FROM users ___ JOIN posts ON posts.user_id = users.id",
              choices: ["LEFT", "INNER", "RIGHT", "OUTER"],
              answer: "LEFT",
              why: "LEFT JOIN keeps the left table (users) intact.",
              concept: "left-join",
            },
            {
              id: "sq-3-2-c",
              kind: "bool",
              prompt: "NULL means the number 0.",
              answer: false,
              why: "NULL is unknown / missing. It is not 0 or ''.",
              concept: "left-join",
            },
          ],
        },
        {
          id: "3",
          title: "COUNT and GROUP BY",
          minutes: 4,
          teach: {
            title: "Aggregate per group",
            body: "COUNT(*) counts rows. Combine with GROUP BY city to count per city. WHERE filters rows before grouping. HAVING filters groups after.",
            code: "SELECT city, COUNT(*) AS n\nFROM users\nGROUP BY city;",
          },
          terms: [
            { term: "COUNT(*)", def: "How many rows" },
            { term: "GROUP BY", def: "Collapse rows that share a value" },
          ],
          questions: [
            {
              id: "sq-3-3-a",
              kind: "fill",
              prompt: "Count rows per city.",
              code: "SELECT city, COUNT(*) FROM users ___ city;",
              choices: ["GROUP BY", "ORDER BY", "PARTITION", "CLUSTER"],
              answer: "GROUP BY",
              why: "GROUP BY city makes one result row per city.",
              concept: "group",
            },
            {
              id: "sq-3-3-b",
              kind: "choice",
              prompt: "Filter groups after aggregation with",
              choices: ["HAVING", "WHERE", "LIMIT", "ON"],
              answer: 0,
              why: "HAVING sees aggregates. WHERE does not.",
              concept: "group",
            },
            {
              id: "sq-3-3-c",
              kind: "bool",
              prompt: "COUNT(*) ignores NULL rows in the table.",
              answer: false,
              why: "COUNT(*) counts rows. COUNT(column) skips NULLs in that column.",
              concept: "group",
            },
          ],
        },
      ],
    },
  ],
};
