import type { Track } from "./types";

export const typescript: Track = {
  id: "typescript",
  name: "TypeScript",
  short: "Ts",
  blurb: "JavaScript with a type checker. Catch bugs before runtime.",
  level: "Beginner",
  chapters: [
    {
      id: "1",
      title: "Types on values",
      summary: "Annotations, inference, unions.",
      clash: {
        name: "Any Creep",
        blurb: "every type collapsed to any. Put the names back.",
      },
      lessons: [
        {
          id: "1",
          title: "Why TypeScript",
          minutes: 3,
          teach: {
            title: "Types are checked, then erased",
            body: "TypeScript is JavaScript plus a type checker. You annotate values. tsc (or your bundler) checks them, then emits plain JS — browsers never see the types. The payoff is errors in the editor instead of in production.",
            code: "const lives: number = 3;\nfunction greet(name: string) {\n  return \"Hi \" + name;\n}",
          },
          terms: [
            { term: "annotation", def: "The : type you write after a name" },
            { term: "tsc", def: "The TypeScript compiler" },
          ],
          questions: [
            {
              id: "ts-1-1-a",
              kind: "fill",
              prompt: "Annotate lives as a number.",
              code: "const lives___ number = 3;",
              choices: [":", "=", "as", "->"],
              answer: ":",
              why: "name: type is the annotation syntax.",
              concept: "annotations",
            },
            {
              id: "ts-1-1-b",
              kind: "choice",
              prompt: "What runs in the browser?",
              choices: [
                "The emitted JavaScript",
                "TypeScript with the types still in it",
                "A special TS virtual machine",
                "Nothing — TS is types only",
              ],
              answer: 0,
              why: "Types are erased. Runtime is JavaScript.",
              concept: "annotations",
            },
            {
              id: "ts-1-1-c",
              kind: "bool",
              prompt: "TypeScript accepts this: const n: number = '3'.",
              answer: false,
              why: "string is not assignable to number.",
              concept: "annotations",
            },
          ],
        },
        {
          id: "2",
          title: "Inference",
          minutes: 3,
          teach: {
            title: "Often you can skip the annotation",
            body: "const lives = 3 infers number. TypeScript still checks later uses. Annotate when the value is empty (let items: string[] = []) or when you want the contract obvious at a boundary (function args and returns).",
            code: "const lives = 3; // inferred number\nlet tags: string[] = [];",
          },
          terms: [
            { term: "inference", def: "TS figures out a type from the value" },
          ],
          questions: [
            {
              id: "ts-1-2-a",
              kind: "choice",
              prompt: "const n = 3 infers",
              choices: ["number", "any", "int", "unknown"],
              answer: 0,
              why: "A numeric literal infers number (or a numeric literal type).",
              concept: "inference",
            },
            {
              id: "ts-1-2-b",
              kind: "fill",
              prompt: "Type an array you will fill later.",
              code: "let tags: ___ = [];",
              choices: ["string[]", "string", "[string]", "Array"],
              answer: "string[]",
              why: "Without an annotation, [] infers never[] / any[] depending on settings.",
              concept: "inference",
            },
            {
              id: "ts-1-2-c",
              kind: "bool",
              prompt: "You must annotate every variable.",
              answer: false,
              why: "Inference covers most locals. Annotate boundaries.",
              concept: "inference",
            },
          ],
        },
        {
          id: "3",
          title: "Union types",
          minutes: 3,
          teach: {
            title: "A value that can be one of several",
            body: "string | number means either. You must narrow before using a side-specific method: if (typeof x === 'string') { x.toUpperCase(); }. | null is how TS models missing values.",
            code: "function id(x: string | number) {\n  return String(x);\n}",
          },
          terms: [
            { term: "union", def: "A | B — one type or the other" },
            { term: "narrowing", def: "Proving which side of a union you have" },
          ],
          questions: [
            {
              id: "ts-1-3-a",
              kind: "fill",
              prompt: "Allow string or null.",
              code: "let name: string ___ null = null;",
              choices: ["|", "||", "or", "&"],
              answer: "|",
              why: "| builds a union. || is the runtime or operator.",
              concept: "unions",
            },
            {
              id: "ts-1-3-b",
              kind: "choice",
              prompt: "Narrow a string | number with",
              choices: ["typeof", "type", "instanceof string", "cast()"],
              answer: 0,
              why: "typeof x === 'string' is the usual primitive narrow.",
              concept: "unions",
            },
            {
              id: "ts-1-3-c",
              kind: "bool",
              prompt: "string | number is both at once.",
              answer: false,
              why: "Union is one or the other, not both. Both at once would be an intersection &.",
              concept: "unions",
            },
          ],
        },
      ],
    },
    {
      id: "2",
      title: "Objects and functions",
      summary: "Interfaces, optional fields, return types.",
      clash: {
        name: "Shapeless Object",
        blurb: "Every property is optional any. Restore the interface.",
      },
      lessons: [
        {
          id: "1",
          title: "interface",
          minutes: 3,
          teach: {
            title: "Name an object shape",
            body: "interface User { id: number; name: string } describes an object. Extra required fields in the value are an error. Use type aliases for unions; interfaces shine for object shapes you might extend.",
            code: "interface User {\n  id: number;\n  name: string;\n}\nconst ada: User = { id: 1, name: \"Ada\" };",
          },
          terms: [
            { term: "interface", def: "A named object shape" },
            { term: "property", def: "A field on an object, like name" },
          ],
          questions: [
            {
              id: "ts-2-1-a",
              kind: "fill",
              prompt: "Name the shape.",
              code: "___ User {\n  id: number;\n}",
              choices: ["interface", "class", "struct", "object"],
              answer: "interface",
              why: "interface declares a shape without emitting runtime code.",
              concept: "interfaces",
            },
            {
              id: "ts-2-1-b",
              kind: "choice",
              prompt: "Which value matches { id: number }?",
              choices: [
                "{ id: 1 }",
                "{ id: '1' }",
                "{ name: 1 }",
                "{ }",
              ],
              answer: 0,
              why: "id must be a number. Missing or string is an error.",
              concept: "interfaces",
            },
            {
              id: "ts-2-1-c",
              kind: "bool",
              prompt: "Interfaces exist at runtime in the emitted JS.",
              answer: false,
              why: "They are erased, like all TS types.",
              concept: "interfaces",
            },
          ],
        },
        {
          id: "2",
          title: "Optional and readonly",
          minutes: 3,
          teach: {
            title: "? and readonly",
            body: "email?: string means the property may be missing. readonly id: number forbids assignment after creation. Optional is not the same as string | undefined written on a required key — the key itself can be absent.",
            code: "interface User {\n  readonly id: number;\n  email?: string;\n}",
          },
          terms: [
            { term: "?", def: "Optional property — may be missing" },
            { term: "readonly", def: "Cannot be reassigned" },
          ],
          questions: [
            {
              id: "ts-2-2-a",
              kind: "fill",
              prompt: "Make email optional.",
              code: "email___: string;",
              choices: ["?", "!", "|", "*"],
              answer: "?",
              why: "A trailing ? on the name marks optional.",
              concept: "optional",
            },
            {
              id: "ts-2-2-b",
              kind: "choice",
              prompt: "Stop id from being reassigned with",
              choices: ["readonly id: number", "final id: number", "const id: number", "id!: number"],
              answer: 0,
              why: "readonly is the modifier. final is Java.",
              concept: "optional",
            },
            {
              id: "ts-2-2-c",
              kind: "bool",
              prompt: "{ id: 1 } matches { id: number; email?: string }.",
              answer: true,
              why: "email is optional, so omitting it is fine.",
              concept: "optional",
            },
          ],
        },
        {
          id: "3",
          title: "Function types",
          minutes: 3,
          teach: {
            title: "Args and returns",
            body: "function add(a: number, b: number): number { return a + b; }. The return annotation is a promise you keep — returning a string is an error. void means no useful return. Arrow forms work too: const add = (a: number, b: number) => a + b;",
            code: "function add(a: number, b: number): number {\n  return a + b;\n}",
          },
          terms: [
            { term: "return type", def: "The : type after the parameter list" },
            { term: "void", def: "A function that does not return a useful value" },
          ],
          questions: [
            {
              id: "ts-2-3-a",
              kind: "fill",
              prompt: "Declare that add returns a number.",
              code: "function add(a: number, b: number)___ number {",
              choices: [":", "=>", "->", "="],
              answer: ":",
              why: "function f(): T is the return annotation.",
              concept: "fn-types",
            },
            {
              id: "ts-2-3-b",
              kind: "choice",
              prompt: "A function that returns nothing useful is typed",
              choices: ["void", "null", "undefined only", "never"],
              answer: 0,
              why: "void. never means it does not return at all (throw/loop).",
              concept: "fn-types",
            },
            {
              id: "ts-2-3-c",
              kind: "bool",
              prompt: "Returning a string from a : number function compiles.",
              answer: false,
              why: "The return annotation is checked.",
              concept: "fn-types",
            },
          ],
        },
      ],
    },
  ],
};
