/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FlashRouteImport } from './routes/flash'
import { Route as LabRouteImport } from './routes/lab'
import { Route as MatchRouteImport } from './routes/match'
import { Route as RecallRouteImport } from './routes/recall'
import { Route as YouRouteImport } from './routes/you'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as LearnLangIdRouteImport } from './routes/learn.$langId'
import { Route as ClashLangIdChapterIdRouteImport } from './routes/clash.$langId.$chapterId'
import { Route as LessonLangIdChapterIdLessonIdRouteImport } from './routes/lesson.$langId.$chapterId.$lessonId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashRoute = FlashRouteImport.update({
  id: '/flash',
  path: '/flash',
  getParentRoute: () => rootRouteImport,
} as any)
const LabRoute = LabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchRoute = MatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => rootRouteImport,
} as any)
const RecallRoute = RecallRouteImport.update({
  id: '/recall',
  path: '/recall',
  getParentRoute: () => rootRouteImport,
} as any)
const YouRoute = YouRouteImport.update({
  id: '/you',
  path: '/you',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnLangIdRoute = LearnLangIdRouteImport.update({
  id: '/learn/$langId',
  path: '/learn/$langId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClashLangIdChapterIdRoute = ClashLangIdChapterIdRouteImport.update({
  id: '/clash/$langId/$chapterId',
  path: '/clash/$langId/$chapterId',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonLangIdChapterIdLessonIdRoute =
  LessonLangIdChapterIdLessonIdRouteImport.update({
    id: '/lesson/$langId/$chapterId/$lessonId',
    path: '/lesson/$langId/$chapterId/$lessonId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/flash': typeof FlashRoute
  '/lab': typeof LabRoute
  '/match': typeof MatchRoute
  '/recall': typeof RecallRoute
  '/you': typeof YouRoute
  '/learn/$langId': typeof LearnLangIdRoute
  '/learn/': typeof LearnIndexRoute
  '/clash/$langId/$chapterId': typeof ClashLangIdChapterIdRoute
  '/lesson/$langId/$chapterId/$lessonId': typeof LessonLangIdChapterIdLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/flash': typeof FlashRoute
  '/lab': typeof LabRoute
  '/match': typeof MatchRoute
  '/recall': typeof RecallRoute
  '/you': typeof YouRoute
  '/learn/$langId': typeof LearnLangIdRoute
  '/learn': typeof LearnIndexRoute
  '/clash/$langId/$chapterId': typeof ClashLangIdChapterIdRoute
  '/lesson/$langId/$chapterId/$lessonId': typeof LessonLangIdChapterIdLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/flash': typeof FlashRoute
  '/lab': typeof LabRoute
  '/match': typeof MatchRoute
  '/recall': typeof RecallRoute
  '/you': typeof YouRoute
  '/learn/$langId': typeof LearnLangIdRoute
  '/learn/': typeof LearnIndexRoute
  '/clash/$langId/$chapterId': typeof ClashLangIdChapterIdRoute
  '/lesson/$langId/$chapterId/$lessonId': typeof LessonLangIdChapterIdLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/flash'
    | '/lab'
    | '/match'
    | '/recall'
    | '/you'
    | '/learn/$langId'
    | '/learn/'
    | '/clash/$langId/$chapterId'
    | '/lesson/$langId/$chapterId/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/flash'
    | '/lab'
    | '/match'
    | '/recall'
    | '/you'
    | '/learn/$langId'
    | '/learn'
    | '/clash/$langId/$chapterId'
    | '/lesson/$langId/$chapterId/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/flash'
    | '/lab'
    | '/match'
    | '/recall'
    | '/you'
    | '/learn/$langId'
    | '/learn/'
    | '/clash/$langId/$chapterId'
    | '/lesson/$langId/$chapterId/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FlashRoute: typeof FlashRoute
  LabRoute: typeof LabRoute
  MatchRoute: typeof MatchRoute
  RecallRoute: typeof RecallRoute
  YouRoute: typeof YouRoute
  LearnLangIdRoute: typeof LearnLangIdRoute
  LearnIndexRoute: typeof LearnIndexRoute
  ClashLangIdChapterIdRoute: typeof ClashLangIdChapterIdRoute
  LessonLangIdChapterIdLessonIdRoute: typeof LessonLangIdChapterIdLessonIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flash': {
      id: '/flash'
      path: '/flash'
      fullPath: '/flash'
      preLoaderRoute: typeof FlashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab': {
      id: '/lab'
      path: '/lab'
      fullPath: '/lab'
      preLoaderRoute: typeof LabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match': {
      id: '/match'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof MatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recall': {
      id: '/recall'
      path: '/recall'
      fullPath: '/recall'
      preLoaderRoute: typeof RecallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/you': {
      id: '/you'
      path: '/you'
      fullPath: '/you'
      preLoaderRoute: typeof YouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$langId': {
      id: '/learn/$langId'
      path: '/learn/$langId'
      fullPath: '/learn/$langId'
      preLoaderRoute: typeof LearnLangIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clash/$langId/$chapterId': {
      id: '/clash/$langId/$chapterId'
      path: '/clash/$langId/$chapterId'
      fullPath: '/clash/$langId/$chapterId'
      preLoaderRoute: typeof ClashLangIdChapterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson/$langId/$chapterId/$lessonId': {
      id: '/lesson/$langId/$chapterId/$lessonId'
      path: '/lesson/$langId/$chapterId/$lessonId'
      fullPath: '/lesson/$langId/$chapterId/$lessonId'
      preLoaderRoute: typeof LessonLangIdChapterIdLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FlashRoute: FlashRoute,
  LabRoute: LabRoute,
  MatchRoute: MatchRoute,
  RecallRoute: RecallRoute,
  YouRoute: YouRoute,
  LearnLangIdRoute: LearnLangIdRoute,
  LearnIndexRoute: LearnIndexRoute,
  ClashLangIdChapterIdRoute: ClashLangIdChapterIdRoute,
  LessonLangIdChapterIdLessonIdRoute: LessonLangIdChapterIdLessonIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
